project:
  title: "Manuscript"
  output-dir: output
  render: 
  - "manuscript.qmd"
  #- "test.qmd"
  #- "test2.qmd"
  - "appendix.qmd"
  - "Manuscript/output/"
  - "Manuscript/Assets/"
  - "Manuscript/Assets/figs/"
  #- "manuscript_full.qmd"

execute: 
  warning: false
  eval: true
  include: true
  freeze: auto
  cache: true
  #echo: false



author:
  - name: Thomas E. Gorman
    url: https://tegorman13.github.io/
    orcid: "0000-0001-5366-5442"
    affiliations: 
      - ref: cclab
      - ref: clara
    attributes: 
      corresponding: true
  - name: Torsten Reimer
    url: https://web.ics.purdue.edu/~treimer/
    orcid: 0000-0002-7419-0076
    affiliations:
      - ref: cclab
      - ref: clara
  - name: Juan Pablo Loaiza Ramirez
    url: https://www.cla.purdue.edu/directory/profiles/loaiza-ramirez,juan-pablo.html
    orcid: 0000-0001-9663-0522
    affiliations:
      - ref: cclab
      - ref: clara
  - name: Hayden Barber
    url: https://www.sdstate.edu/directory/hayden-barber
    orcid: 0000-0002-3465-8615
    affiliations:
      - ref: sdsu
affiliations:
  - id: cclab
    name: Communication and Cognition Lab, Purdue University
    city: West Lafayette
    region: IN
    country: USA
    postal-code: 47907
    url: https://web.ics.purdue.edu/~treimer/
  - id: clara
    name: College of Liberal Arts Research Academy
    department: Purdue University
    city: West Lafayette
    region: IN
    country: USA
    postal-code: 47907
    url: https://cla.purdue.edu/about/college-initiatives/research-academy/
  - id: sdsu
    name: School of Communication & Journalism, South Dakota State University
    city: Brookings
    region: SD
    country: USA
    url: https://www.sdstate.edu/directory/hayden-barber

format: 
  code_apa-html: 
    echo: true
    code-fold: show
    output-file: manuscript-code.html
    floatsintext: true
    wordcount-banner: true
    theme: 
      - zephyr
      - ../assets/custom.scss
    toc: true
    shift-heading-level-by: 1
    code-summary: "Show the code"
    title-block-banner: "#000D51"
    include-in-header:
        - text: |
            <style type="text/css">
            h2.hide {
                display: none;
            }
            </style>
  wordcount_apa-html: 
    #output-file: index.html
    wordcount-banner: true
    floatsintext: true
    echo: false
    theme: 
        - zephyr
        - ../assets/custom.scss
    toc: true
    shift-heading-level-by: 1
    title-block-banner: "#000D51"
    include-in-header:
        - text: |
            <style type="text/css">
            h2.hide {
                display: none;
            }
            </style>
  # docx: 
  #   echo: false
  # hikmah-manuscript-docx: 
  #   output-file: hikmah_manuscript.docx
  #   echo: false
  apaquarto-docx: 
    output-file: rs_manuscript_apa.docx
    echo: false
    floatsintext: true
    shorttitle: "How Information Format Affects Accuracy"
    author-note:
      disclosures:
        conflict of interest: The authors have no conflict of interest to declare.
  hugo-md:
    include: false
    echo: false
    html-math-method: mathjax
    output-file: manuscript_hugo.md
    suppress-bibliography: false
  gfm:
    echo: true
    output: asis
    output-file: manuscript_gfm.md
    suppress-bibliography: true
  apaquarto-pdf: 
    toc: false
    echo: false
    #output-file: rs_apa_code.pdf
    output-file: rs_manuscript_apa.pdf
    floatsintext: true
    author-note:
      disclosures:
        conflict of interest: The authors have no conflict of interest to declare.
  # hikmah-manuscript-pdf:
  #   output-file: rep_study.pdf
  #   echo: false
  #   mainfont: "Linux Libertine O"
  #   mainfontoptions:
  #   - "Numbers=Proportional"
  #   - "Numbers=OldStyle"
  #   mathfont: "Libertinus Math"
  #   knitr:
  #       opts_chunk:
  #           dev: "cairo_pdf"


  apaquarto-html:
    #output-file: index.html
  # wordcount-banner: true
    output-file: rs_manuscript_apa.html
    echo: false
    floatsintext: true
    theme: 
        - zephyr
        - ../assets/custom.scss
    toc: true
    shift-heading-level-by: 1
    title-block-banner: "#000D51"
    include-in-header:
        - text: |
            <style type="text/css">
            h2.hide {
                display: none;
            }
            </style>

keywords: ["Information format", "Energy literacy", "Decision-making", "Planning"]


bibliography: ../assets/rs_bib.bib
csl: ../assets/apa.csl
google-scholar: false


# profile:
#   group: 
#     - [plain, nice,thesis, ms, md]