---
title: "Planning to Save Energy: How Information Format Affects Accuracy"
author:
  - name: Thomas E. Gorman
    url: https://tegorman13.github.io/
    orcid: "0000-0001-5366-5442"
    affiliations: 
      - ref: cclab
      - ref: clara
    attributes: 
      corresponding: true
  - name: Torsten Reimer
    url: https://web.ics.purdue.edu/~treimer/
    orcid: 0000-0002-7419-0076
    affiliations:
      - ref: cclab
      - ref: clara
  - name: Juan Pablo Loaiza Ramirez
    url: https://www.cla.purdue.edu/directory/profiles/loaiza-ramirez,juan-pablo.html
    orcid: 0000-0001-9663-0522
    affiliations:
      - ref: cclab
      - ref: clara
  - name: Hayden Barber
    url: https://www.sdstate.edu/directory/hayden-barber
    orcid: 0000-0002-3465-8615
    affiliations:
      - ref: sdsu
affiliations:
  - id: cclab
    name: Communication and Cognition Lab, Purdue University
    city: West Lafayette
    region: IN
    country: USA
    postal-code: 47907
    url: https://web.ics.purdue.edu/~treimer/
  - id: clara
    name: College of Liberal Arts Research Academy
    department: Purdue University
    city: West Lafayette
    region: IN
    country: USA
    postal-code: 47907
    url: https://cla.purdue.edu/about/college-initiatives/research-academy/
  - id: sdsu
    name: School of Communication & Journalism, South Dakota State University
    city: Brookings
    region: SD
    country: USA
    url: https://www.sdstate.edu/directory/hayden-barber
format:
    # html: 
    #     grid:
    #         sidebar-width: 220px
    #         body-width: 1200px
    #         margin-width: 170px
    #         gutter-width: 1.0rem
    wordcount-html: 
        #output-file: index.html
        wordcount-banner: true
        theme: 
            - zephyr
            - ../assets/custom.scss
        toc: true
        shift-heading-level-by: 1
        code-fold: true
        code-summary: "Show the code"
        title-block-banner: "#000D51"
        include-in-header:
            - text: |
                <style type="text/css">
                h2.hide {
                    display: none;
                }
                </style>
    hugo-md:
        include: true
        echo: false
        html-math-method: mathjax
        output-file: test_hugo.md
    gfm:
        echo: true
        output-file: test_gfm.md
    hikmah-manuscript-pdf:
        output-file: test.pdf
        mainfont: "Linux Libertine O"
        mainfontoptions:
        - "Numbers=Proportional"
        - "Numbers=OldStyle"
        mathfont: "Libertinus Math"
        knitr:
            opts_chunk:
                dev: "cairo_pdf"
    hikmah-manuscript-docx: default
# format-links:   
#     - html
#     - gfm
#     - format: hikmah-manuscript-pdf
#       text: PDF version
#       icon: file-pdf
date: 2024-12-03
abstract: |
    This study aims to examine how the format of energy information impacts individuals’ ability to develop precise energy reduction plans. By manipulating the reference class (kWh, %, USD) and assessing planning accuracy, we seek to determine which format facilitates better comprehension and decision-making.Across two experiments, the kWh format generally led to better accuracy, while the USD format consistently led to the worst performance. These findings highlight the importance of effective information presentation to promote energy conservation, and may contribute to the development of more effective energy communication strategies that can enhance conservation efforts.
---


This study aims to examine how the format of energy information impacts individuals’ ability to develop precise energy reduction plans. By manipulating the reference class (kWh, %, USD) and assessing planning accuracy, we seek to determine which format facilitates better comprehension and decision-making.Across two experiments, the kWh format generally led to better accuracy, while the USD format consistently led to the worst performance. These findings highlight the importance of effective information presentation to promote energy conservation, and may contribute to the development of more effective energy communication strategies that can enhance conservation efforts.




# Introduction


- highlight the significant contribution of residential energy consumption to carbon emissions and the potential for substantial reductions. Make point about urgency of climate change? (IPCC (2014) and EIA (2012) ).

- Electricity bills are a primary source of energy-use information for consumers and offer a promising avenue for enhancing communication about energy consumption [@fischerFeedbackHouseholdElectricity2008]


### Literature Review

- @canfieldPerceptionsElectricityuseCommunications2017 found that tables were more effective than graphs for conveying specific electricity usage data, likely because tables facilitate straightforward point reading. However, they also noted that individuals with lower energy literacy had reduced comprehension across all formats.
- @canfieldPerceptionsElectricityuseCommunications2017's findings on preferences for historical use information and the impact of neighbor comparisons


- alignment can reduce cognitive load and enhance accuracy in planning [@shahBarLineGraph2011]
- Reimer et al. (2015) provide  context on how numerical formats affect risk perception, the reference class problem, and the benefits of natural frequencies.


Energy poverty continues to be a pervasive issue in the United States @memmottSociodemographicDisparitiesEnergy2021. This challenge partly arises from difficulties in converting information across numerical formats, impeding the development of precise energy reduction plans @reimerNumericCommunicationRisk2015. Prior research by @canfieldPerceptionsElectricityuseCommunications2017 demonstrated that presenting energy information in tabular formats enhances comprehension relative to graphs. 


The way numerical information is presented can significantly affect how individuals process and use that information [@reimerNumericCommunicationRisk2015] . The reference class problem highlights that numbers without clear reference points can lead to misinterpretation, as the meaning of a statistic depends on the category or class it refers to [@gigerenzerSimpleToolsUnderstanding2003; @reimerNumericCommunicationRisk2015]. Presenting energy information in absolute units (e.g., kWh) provides a clear reference class, potentially enhancing comprehension.

Furthermore, research suggests that natural frequencies and absolute numbers are generally easier for individuals to understand compared to percentages or probabilities [@gigerenzerHowImproveBayesian1995 @hoffrageCommunicatingStatisticalInformation2000]. In the context of energy conservation, using absolute units may facilitate more accurate planning and decision-making by aligning with intuitive cognitive processing.

Despite existing studies on energy-use communication and format effects, limited research has explored how different numerical representations influence consumers’ ability to create accurate energy conservation plans. Specifically, there is a gap in understanding how presenting energy information in absolute units versus percentages or monetary terms affects the precision of planning appliance-specific reductions. Addressing this gap is crucial for developing effective interventions that promote energy conservation behaviors.




@abrahamseReviewInterventionStudies2005

@attariEnablingEnergyConservation2015

@dewatersEnergyLiteracySecondary2011

@gigerenzerSimpleToolsUnderstanding2003

@larrickMPGIllusion2008

@blaschBoundedlyRationalConsumers2019

@fischerFeedbackHouseholdElectricity2008

@schwartzWhatPeopleConsumption2015

@vongrabeUsingInstanceBasedLearning2020

@gigerenzerHowImproveBayesian1995

@attariPublicPerceptionsEnergy2010

@herrmannDoesDataVisualization2018

@vandenbroekHeuristicsEnergyJudgement2019

@herberzKiloWhatDefault2020

@marghetisSimpleInterventionsCan2019

@lagomarsinoNeedChargeRight2022

@hahnelMentalAccountingMechanisms2020

@delgadoOpportunitiesGreaterEnergy2018

@schleyCognitiveAccessibilityJudgments2015

@langeWorkEnvironmentalProtection2021

@tiedeNumeracyNumericAttention2022




### Hypotheses

Building on these findings and informed by prior work showing that frequencies (like absolute units in kWh) are easier to comprehend and facilitate more precise decision-making compared to percentages, our study also utilizes a tabular format, but manipulates whether participants must consider energy information presented as absolute units (kWh), percentages (%), or monetary costs (USD). We hypothesize that presenting information in absolute units (kWh) will lead to more accurate household energy conservation planning.





# Experiment 1

See @fig-task for an example of a planning trial as it was seen by participants.

## Methods

### Participants

We implemented our task and surveys on Qualtrics, and recruited participants through Amazon Mechanical Turk. In Experiment 1, 252 participants were intially recruited, but data from 17 participants were corrupted due to experimenter error, leaving a final sample of 235 participants. Most participants (76%) reported using a calculator to complete the task. 


### Materials and Design 

The study employed a mixed design with reference class (kWh, percentage, USD) as a between-subjects factor and state/family scenario as a within-subjects factor. Each participant completed energy reduction planning tasks for two different states, with state order counterbalanced across participants. The family scenarios featured four households in different climate regions: Texas (Smith family) and California (Adams family) representing warm climates, and Colorado (Wells family) and Massachusetts (Davis family) representing cold climates. We obtain average utility use from each state by CITE SOURCE FOR STATE AVGS? 


### Procedure

Participants received energy usage data for two hypothetical families and were tasked with creating action plans to meet specified reduction goals by allocating usage across five appliance categories:  heating, cooling, water heating, refrigerator, and an other appliances (e.g., TV, lighting).


Additional data collected included:

-   **Energy Literacy Quiz**: An 8-item questionnaire assessing participants' knowledge of energy consumption and conversion.
-   **Calculator Usage Tracking**: Questions determined whether participants used a calculator, paper/pen, or other methods to complete the tasks.
-   **Demographic Survey**: Collected information on gender, age, income, education, employment status, and state of residence.
-   **Environmental Attitudes Survey**: Assessed participants' pro-environmental attitudes and perceived importance of energy conservation.

