  project:
    output-dir: .
    type: default
    render:
      - "*.qmd"
      - "!_*"

  format:
    pdf: 
      echo: false
      documentclass: article
      #papersize: custom
      keep-tex: true
      toc: false
      fontsize: 12pt
      linestretch: 1.01
      geometry:
          - paperwidth=42in
          - paperheight=25in
          #- margin=.2in
          - top=.2in        # << ADJUST THIS: Make it large enough for your header (~ TikZ height + buffer)
          - bottom=0.5in   # << Set desired bottom margin
          - left=0.5in     # << Set desired left margin
          - right=0.5in    # << Set desired right margin
          - columnsep=0.75in # Adjust space between columns
      include-in-header:
        text: |
          \usepackage[T1]{fontenc}       % Use modern font encoding
          \usepackage{helvet}            % Use Helvetica clone (sans-serif)
          \renewcommand\familydefault{\sfdefault} % Make sans-serif the default font family
          \usepackage{graphicx}          % Required for images
          \usepackage{amsmath}           % For math symbols if needed
          \usepackage{amssymb}           % For math symbols if needed
          \usepackage{textcomp}          % For symbols like degrees
          \usepackage{xcolor}            % For color definitions
          \usepackage{multicol}          % For multi-column layout
          \usepackage{geometry}          % To set paper size and margins (already used by Quarto, but good practice)
          \usepackage{fancyhdr}          % For headers and footers
          % \usepackage{titlesec}          % For customizing section titles
          \usepackage{sectsty}           % Alternative/complement to titlesec for section fonts
          \usepackage{enumitem}          % For customizing lists (itemize, enumerate)
          \usepackage{caption}           % For customizing figure/table captions
          \usepackage{subcaption} 
          \usepackage{hyperref}          % For clickable links (references, URLs)
          \usepackage{tikz}              % For drawing header/footer backgrounds
          \usepackage{subcaption}
          \usepackage{amsfonts}
          \usepackage{etoolbox}
          \usepackage{titletoc}        % For table of contents customization
          \usepackage[explicit]{titlesec}  % For section title customization with explicit option
          \usepackage{caption}
          \captionsetup[figure]{labelformat=empty}% redefines the caption setup of the figures environment in the beamer class.


          % --- Color Definitions ---
          \definecolor{purduegold}{HTML}{CEB888} % Keep original Purdue Gold
          \definecolor{purdueblack}{HTML}{000000}
          \definecolor{purduegray}{HTML}{5F6062}  % Keep original Purdue Gray
          \definecolor{sectionbg}{HTML}{D6C8A3}  % New tan/beige color for section headers
          \definecolor{lightgold}{HTML}{FBF8F1}  % A lighter shade for backgrounds
          \definecolor{darkgray}{HTML}{333333}   % Darker Gray for text contrast

          % --- SET BASE FONT SIZE HERE (Overrides any default/cached \normalsize) ---
          \makeatletter
          \renewcommand{\normalsize}{%
              \@setfontsize\normalsize{19.5pt}{22pt}% Main font size and line spacing
              \abovedisplayskip 12pt plus 3pt minus 7pt
              \abovedisplayshortskip \z@ plus 3pt
              \belowdisplayshortskip 6.5pt plus 3.5pt minus 3pt
              \belowdisplayskip \abovedisplayskip
              \let\@listi\@listI}
          \makeatother

          % Adjust other font size commands to be in proportion to normalsize
          \makeatletter
          \renewcommand{\large}{\@setfontsize\large{18pt}{24pt}}
          \renewcommand{\Large}{\@setfontsize\Large{20pt}{26pt}}
          \renewcommand{\LARGE}{\@setfontsize\LARGE{24pt}{30pt}}
          \renewcommand{\huge}{\@setfontsize\huge{28pt}{36pt}}
          \renewcommand{\Huge}{\@setfontsize\Huge{34pt}{42pt}}
          \makeatother

          \normalsize  % Activate the new normal size definition


          % --- Font & Section Styling ---
          % Using sectsty for simplicity here
          \sectionfont{\color{darkgray}\huge\bfseries\sffamily\raggedright} % Make section titles large, bold, dark gray
          \subsectionfont{\color{darkgray}\Large\bfseries\sffamily\raggedright} % Make subsection titles large, bold, dark gray
          \subsubsectionfont{\color{purduegray}\large\bfseries\sffamily\raggedright} % Make subsubsection titles medium, bold, gray

          % --- ADJUST SPACING HERE ---
          % Reduce space AFTER section titles and BEFORE subsections/subsubsections
          % Format: \titlespacing*{<command>}{<left>}{<before-sep>}{<after-sep>}
          \titlespacing*{\section}
            {0pt}               % Left margin
            {.3ex plus 0.2ex minus .0ex} % Space BEFORE title (reduced slightly)
            {0.3ex plus .1ex}   % Space AFTER title (SIGNIFICANTLY REDUCED from 1ex or more)

          \titlespacing*{\subsection}
            {0pt}               % Left margin
            {.1ex plus 0.1ex minus .0ex} % Space BEFORE title (reduced slightly)
            {0.1ex plus .1ex}   % Space AFTER title (REDUCED)

          \titlespacing*{\subsubsection}
            {0pt}               % Left margin
            {0.1ex plus 0.1ex minus .2ex} % Space BEFORE title (reduced slightly)
            {0.0ex plus .02ex}   % Space AFTER title (REDUCED)

          % --- List Styling ---
          \setlist[itemize]{leftmargin=1.5em, label=\textbullet, itemsep=0.4ex, topsep=0.05ex} % Adjust bullet indentation and spacing
          \setlist[enumerate]{leftmargin=1.5em, itemsep=0.2ex, topsep=0.5ex}

          % --- ADJUST LIST SPACING HERE ---
          % Reduce space BEFORE the entire list starts
          \setlist[itemize]{
            leftmargin=1.5em,     % Indentation
            label=\textbullet,    % Bullet style
            itemsep=0.2ex,        % Space between items in the list
            topsep=0.0ex          % Space BEFORE the first item (SIGNIFICANTLY REDUCED from 0.5ex or more)
          }
          \setlist[enumerate]{
            leftmargin=1.5em,
            itemsep=0.2ex,
            topsep=0.2ex          % Space BEFORE the first item (REDUCED)
          }


          % --- Section Header Styling ---
          % Define the section background color first
          \definecolor{sectionbg}{HTML}{D6C8A3}  % Tan/beige color for section headers

          % Use a simpler approach for section styling without relying on TikZ nodes
          \titleformat{\section}
            {\normalfont\Large\bfseries\sffamily}
            {}
            {0pt}
            {\colorbox{sectionbg}{\parbox{\dimexpr\columnwidth-2\fboxsep\relax}{\centering#1}}}
            []

          % For unnumbered sections
          \titleformat{name=\section,numberless}
            {\normalfont\Large\bfseries\sffamily}
            {}
            {0pt}
            {\colorbox{sectionbg}{\parbox{\dimexpr\columnwidth-2\fboxsep\relax}{\centering#1}}}
            []

          % Adjust spacing around sections
          \titlespacing*{\section}
            {0pt}
            {1.5ex plus 0.5ex minus 0.2ex}
            {1.0ex plus 0.2ex}

          % --- Header and Footer Styling ---
          \pagestyle{fancy} % Use fancyhdr
          \fancyhf{}       % Clear default header/footer
          \renewcommand{\headrulewidth}{0pt} % No header rule
          \renewcommand{\footrulewidth}{0pt} % No footer rule
          % Footer content is added via tikz overlay in after-body.tex


          \DeclareCaptionFont{subcapstyle}{\sffamily\fontsize{16pt}{19pt}\selectfont}

          % --- Figure Caption Styling ---
          \captionsetup{
            font={normalsize, sf},          % Small sans-serif font for captions
            labelfont={bf, color=darkgray}, % Bold, dark gray label (e.g., "Figure 1:")
            labelsep=period,           % Use period after label
            justification=raggedright, % Left-align caption text
            singlelinecheck=false,     % Ensure justification applies even to single lines
            skip=1ex                   % Space between figure and caption
          }

          \captionsetup[subfigure]{font=subcapstyle} 


          % --- Hyperlink Styling ---
          \hypersetup{
            colorlinks=true,          % Enable colored links
            linkcolor=purduegray,     % Color for internal links (e.g., refs)
            citecolor=purduegray,     % Color for citation links
            filecolor=purduegray,     % Color for file links
            urlcolor=purduegray,      % Color for URL links
            pdftitle={Planning to Save Energy: How Information Format Affects Accuracy}, % PDF metadata
            pdfauthor={Thomas E. Gorman et al.} % PDF metadata
          }
          \AtBeginEnvironment{CSLReferences}{\footnotesize} 
      template-partials:
        - before-body.tex
        - after-body.tex

  bibliography: ../assets/rs_bib.bib
  csl: ../assets/apa.csl