{
  "hash": "dabd9034e15d7d44084008e106ca5f74",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Planning to Save Energy: How Information Format Affects Accuracy\"\naliases:\n  - /manuscript.html\nformat:\n    wordcount-html: \n        #output-file: index.html\n        wordcount-banner: true\n        theme: \n            - zephyr\n            - ../assets/custom.scss\n        toc: true\n        shift-heading-level-by: 1\n        title-block-banner: \"#000D51\"\n        include-in-header:\n            - text: |\n                <style type=\"text/css\">\n                h2.hide {\n                    display: none;\n                }\n                </style>\n    html: \n      echo: true\n      code-fold: show\n      output-file: manuscript-code.html\n    hugo-md:\n        include: false\n        echo: false\n        html-math-method: mathjax\n        output-file: manuscript_hugo.md\n        suppress-bibliography: true\n    gfm:\n        echo: true\n        output-file: manuscript_gfm.md\n        suppress-bibliography: true\n    hikmah-manuscript-pdf:\n        output-file: rep_study.pdf\n        mainfont: \"Linux Libertine O\"\n        mainfontoptions:\n        - \"Numbers=Proportional\"\n        - \"Numbers=OldStyle\"\n        mathfont: \"Libertinus Math\"\n        knitr:\n            opts_chunk:\n                dev: \"cairo_pdf\"\n    #hikmah-manuscript-docx: default\n    docx: default\nformat-links:   \n    - text: HTML\n      href: manuscript.html\n      icon: file-minus\n    - text: HTML (with code)\n      href: manuscript-code.html\n      icon: file-plus\n    - format: hikmah-manuscript-pdf\n      text: PDF version\n      icon: file-pdf\n    - docx\n    - gfm\ndate: 2024-12-07\nabstract: |\n    Effective communication of energy consumption information is crucial for promoting residential energy conservation. This study investigates how different numerical representations of energy reduction goals influence consumers' ability to create accurate conservation plans. Across two experiments, we examined the impact of presenting energy information in kilowatt-hours (kWh), percentages, or U.S. dollars (USD) on planning accuracy. Participants completed a simulated household planning task in which they allocated energy usage across multiple appliances, with the goal presented in either kilowatt-hours (kWh), percentages, or monetary costs. Results across both experiments showed that presenting reduction goals in absolute units (kWh) led to significantly greater accuracy compared to percentage-based or monetary formats. Furthermore, we found that higher energy literacy was associated with more accurate planning. These findings demonstrate that absolute units (kWh) are more effective for communicating energy-saving goals, and highlight the potential value of educational interventions to improve consumer energy literacy.\n---\n\n\n\n\n\n\n\n\n\n# Introduction\n\n\n- highlight the significant contribution of residential energy consumption to carbon emissions and the potential for substantial reductions. Make point about urgency of climate change? (IPCC (2014) and EIA (2012) ).\n\n- Electricity bills are a primary source of energy-use information for consumers and offer a promising avenue for enhancing communication about energy consumption [@fischerFeedbackHouseholdElectricity2008]\n\n\n### Literature Review\n\n\n\nEnergy poverty continues to be a pervasive issue in the United States [@memmottSociodemographicDisparitiesEnergy2021]. This challenge partly arises from difficulties in converting information across numerical formats, impeding the development of precise energy reduction plans @reimerNumericCommunicationRisk2015. Prior research by @canfieldPerceptionsElectricityuseCommunications2017 demonstrated that presenting energy information in tabular formats enhances comprehension relative to graphs. \n\n\nThe way numerical information is presented can significantly affect how individuals process and use that information [@reimerNumericCommunicationRisk2015]. The reference class problem highlights that numbers without clear reference points can lead to misinterpretation, as the meaning of a statistic depends on the category or class it refers to [@gigerenzerSimpleToolsUnderstanding2003; @reimerNumericCommunicationRisk2015]. Presenting energy information in absolute units (e.g., kWh) provides a clear reference class, potentially enhancing comprehension.\n\n\nThe concept of cognitive fit posits that performance improves when the information presentation format aligns with the task requirements [@vesseyCognitiveFitTheoryBased1991], and that such an alignment can reduce cognitive load and enhance accuracy in planning [@shahBarLineGraph2011]. For instance, tables are generally more effective than graphs for conveying specific electricity usage data because they facilitate straightforward point reading [@canfieldPerceptionsElectricityuseCommunications2017]. However, the effectiveness of the format varies with the type of information and individual differences, such as energy literacy, which significantly impacts comprehension and conservation intent. Moreover, the unit in which numerical information is presented influences how decision-makers evaluate and choose between options, with default units increasing value sensitivity [@herberzKiloWhatDefault2020]. In the context of energy, presenting information in terms of multiple translations can increase preference for options aligned with activated objectives, such as pro-environmental values [@ungemachTranslatedAttributesChoice2018]. Furthermore, mental accounting mechanisms, where individuals create mental budgets linking specific consumption acts to specific payments, significantly impact energy decisions and behaviors [@hahnelMentalAccountingMechanisms2020]. \n\nEvidence from research on energy consumption feedback, normative comparisons, and eco-feedback platforms suggests that comprehensible and contextually meaningful data presentations can improve users’ ability to plan reductions, especially when these formats are integrated into daily routines [@canfieldPerceptionsElectricityuseCommunications2017; @fischerFeedbackHouseholdElectricity2008; @kimMySmartEEcofeedbackGaming2022; @schwartzWhatPeopleConsumption2015]. Furthermore, temporal and monetary frames have been shown to alter decision quality, with monthly costs or absolute consumption levels often encouraging more energy-efficient intentions than abstract annual or percentage-based metrics [@gillConsumerMatchingCosts2022; @larrickMPGIllusion2008]. In this context, tailoring reference classes to align with intuitive cognitive processes can help bridge the gap between aggregate reduction goals and targeted, appliance-specific conservation strategies.\n\n\n\nFurthermore, research suggests that natural frequencies and absolute numbers are generally easier for individuals to understand compared to percentages or probabilities [@gigerenzerHowImproveBayesian1995 @hoffrageCommunicatingStatisticalInformation2000]. In the context of energy conservation, using absolute units may facilitate more accurate planning and decision-making by aligning with intuitive cognitive processing.\n\nDespite existing studies on energy-use communication and format effects, limited research has explored how different numerical representations influence consumers’ ability to create accurate energy conservation plans. Specifically, there is a gap in understanding how presenting energy information in absolute units versus percentages or monetary terms affects the precision of planning appliance-specific reductions. Addressing this gap is crucial for developing effective interventions that promote energy conservation behaviors.\n\n### Hypotheses\n\nBuilding on these findings and informed by prior work showing that frequencies (like absolute units in kWh) are easier to comprehend and facilitate more precise decision-making compared to percentages, our study also utilizes a tabular format, but manipulates whether participants must consider energy information presented as absolute units (kWh), percentages (%), or monetary costs (USD). We hypothesize that presenting information in absolute units (kWh) will lead to more accurate household energy conservation planning.\n\n\n\n\n\n# Experiment 1\n\nSee @fig-task for an example of a planning trial as it was seen by participants.\n\n## Methods\n\n### Participants\n\nWe implemented our task and surveys on Qualtrics, and recruited participants through Amazon Mechanical Turk. In Experiment 1, 252 participants were initially recruited, but data from 17 participants were corrupted due to experimenter error, leaving a final sample of 235 participants. Most participants (76%) reported using a calculator to complete the task. \n\n\n### Materials and Design \n\nThe study employed a mixed design with reference class (kWh, percentage, USD) as a between-subjects factor and state/family scenario as a within-subjects factor. Each participant completed energy reduction planning tasks for two different states, with state order counterbalanced across participants. The family scenarios featured four households in different climate regions: Texas (Smith family) and California (Adams family) representing warm climates, and Colorado (Wells family) and Massachusetts (Davis family) representing cold climates. We obtain average utility use from each state by CITE SOURCE FOR STATE AVGS? \n\n\n### Procedure\n\nParticipants received energy usage data for two hypothetical families and were tasked with creating action plans to meet specified reduction goals by allocating usage across five appliance categories:  heating, cooling, water heating, refrigerator, and and other appliances (e.g., TV, lighting).\n\nFor each family scenario, the participants were shown a table containing the families utility usage from the prior year, alongside the state averages for each appliance category (both prior year usage and stage averages are always shown in kWh). For each scenario, participants were asked to create two possible action plans to achieve the target reduction in total household energy usage (see @fig-task). Depending on their reference class condition, the target reduction amount presented either in kilowatt-hours (kWh), as percentages of total household usage, or in U.S. dollars. In all conditions, the target reduction was equivalent to a 15% reduction in total household kWh. \n\n![Example trial in the energy planning task. Participants are shown the prior year electricity use of a household, and are tasked with creating a plan for the next year that will meet the energy reduction goal. Study 1 manipulates the format of the reduction goal to be either a percentage (15% given as goal reduction), kilowatt hours (5965 kWh given), or USD (\\$656)](/assets/images/Smith_10R_Wells_15E.png){#fig-task}\n\n\nAdditional data collected included:\n\n-   **Energy Literacy Quiz**: An 8-item questionnaire assessing participants' knowledge of energy consumption and conversion [ @dewatersEnergyLiteracySecondary2011].\n-   **Calculator Usage Tracking**: Questions determined whether participants used a calculator, paper/pen, or other methods to complete the tasks.\n\n\n\n\n\n\n\n## Results\n\n\n### Data Analysis\n\nAll preprocessing and analyses were carried out in R [@rcoreteamLanguageEnvironmentStatistical2020] and the tidyverse package [@wickhamWelcomeTidyverse2019]. Mixed Bayesian regressions were fit using the brms package [@burknerBrmsPackageBayesian2017], with participants and family scenario (states) set as random effects. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n::: {#tbl-s1-agg}\n\n|Reference Class |Avg. % Change |% meeting goal (exact) |% meeting goal (close match) |Abs. Deviation |Log Abs. Deviation |\n|:---------------|:-------------|:----------------------|:----------------------------|:--------------|:------------------|\n|kWh             |0.22          |0.38                   |0.54                         |0.03           |-3.7               |\n|Percentage      |0.21          |0.22                   |0.40                         |0.06           |-3.1               |\n|USD             |0.23          |0.10                   |0.22                         |0.10           |-2.4               |\n\nStudy 1: Summary of planning accuracy by reference class. The table shows performance as both the % of trials where participants matched the goal, and the mean absolute error from the target reduction goal\n\n:::\n\n@tbl-s1-agg that participants in the kWh condition met the target goal 38% of the time, compared to 22% for the Percentage condition and 10% for the USD condition. Moreover, the kWh reference class exhibited smaller deviations from the target reduction, suggesting that participants performed more accurately when the goal was framed in kWh rather than when percentages or USD.\n\n\nAs shown in @tbl-s1-agg, participants in the kWh condition exactly met the target reduction goal 38% of the time, significantly outperforming those in the Percentage (22%) and USD (10%) conditions. Furthermore, the kWh reference class exhibited notably smaller mean absolute deviations (0.03) compared to Percentage (0.06) and USD (0.10), suggesting that presenting the reduction goal in absolute units facilitated more precise allocations. \n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Study 1: Distribution of log absolute error by reference class.](manuscript_files/figure-docx/fig-s1-log-dist-1.png){#fig-s1-log-dist}\n:::\n:::\n\n::: {#tbl-s1-prop .cell tbl-cap='Study 1: The table shows the percentage of participants who fell into each accuracy level for each reference class condition (percentages of kWh, $, and USD columns reflect within condition percentages). The combined group column reflects the percentage of participants in each accuracy level when aggregating across across all reference class conditions.'}\n::: {.cell-output-display}\n\n\n|Accuracy Level |kWh   |Percentage |USD   |Combined Groups % |\n|:--------------|:-----|:----------|:-----|:-----------------|\n|Exact match    |37.5% |22.1%      |9.8%  |22.6%             |\n|0.01-2% error  |15.1% |17.6%      |11.2% |14.4%             |\n|2.01-15% error |27.6% |43.4%      |49.2% |40.3%             |\n|Over 15% error |19.9% |16.9%      |29.8% |22.8%             |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe next categorized responses into three accuracy levels (exact match [0% error], minor deviations [0.01–5%], and large deviations [>5%]) for our primary statistical modeling. Using Bayesian ordinal regression, we modeled the ordered accuracy outcome as a function of the reference class condition, while controlling for random variation across participants and family scenarios:\n\n$$\n\\text{Accuracy Level} \\sim \\text{Reference Class} + \\text{Calculator} + (1|\\text{id}) + (1|\\text{Family Scenario})\n$$\n\n\nThis approach allowed us to estimate thresholds (intercepts) and regression coefficients that capture how different reference classes affect the likelihood of achieving higher accuracy categories. For each comparison, we provide posterior odds ratios (OR) and their 95% CIs. This approach allows the estimation of threshold parameters and regression coefficients that characterize how changes in predictor variables (such as the reference class: kWh, percentage, or USD) relate to probabilities of being in each accuracy category.\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n::: {#tbl-s1-reg}\n\n|Parameter          |Estimate |CI_Lower |CI_Upper |pd   |\n|:------------------|:--------|:--------|:--------|:----|\n|Intercept[1]       |-4.21    |-5.90    |-2.58    |1.00 |\n|Intercept[2]       |-0.89    |-2.49    |0.71     |0.87 |\n|refClassPercentage |1.44     |0.07     |2.88     |0.98 |\n|refClassUSD        |3.13     |1.81     |4.50     |1.00 |\n|calcUsedCalculator |-3.30    |-4.80    |-1.92    |1.00 |\n\n**Experiment 1**: Ordinal Regression results. Ordinal regression results. Positive coefficients for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline.\n\n:::\n\n::: {#tbl-s1-ord}\n|Comparison        |odds_ratio |ci_lower |ci_upper |\n|:-----------------|:----------|:--------|:--------|\n|Percentage vs kWh |4.2        |1.1      |18       |\n|USD vs kWh        |22.9       |6.1      |90       |\n\n\n**Experiment 1**: Odds ratios for group comparisons. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition.\n\n:::\n\n\nAs shown in @tbl-s1-reg, the reference class coefficients are positive for both the Percentage (Estimate = 1.3, 95% CI: 0.01 to 2.66, pd = 0.98) and USD (Estimate = 2.8, 95% CI: 1.52 to 4.04, pd = 1.00) conditions, relative to the kWh baseline. This indicates that, compared to the kWh condition, participants in both the Percentage and USD conditions were more likely to produce plans that fell into higher error categories. Moreover, the odds ratios (see Table 3) suggest that the USD condition led to a notably higher likelihood of large errors compared to the kWh baseline (OR = 15.7), while the Percentage condition also demonstrated increased odds (OR = 3.7) but was somewhat less detrimental to accuracy than USD. These results align with our descriptive findings and further clarify that framing the target reductions in absolute kWh units may facilitate significantly more accurate planning. Posterior predictive checks showed that the ordinal model provided a reasonable fit to the observed data (see @fig-s1-ppd).\n\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Study 1: Proportion of participants in each accuracy level, colored by reference class, and seprated in facets based on the levels of reduction goal.  A larger % of participants in the Exact Match, or 0.01-2% error bins indicates better performance.](manuscript_files/figure-docx/fig-s1-ppd-1.png){#fig-s1-ppd}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 1. Conditional effect of energy literacy on log absolute error. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.](manuscript_files/figure-docx/fig-s1-els-1.png){#fig-s1-els}\n:::\n:::\n\n\n\n\n\n\n\n\n\nTo further investigate individual factors that may influence planning accuracy, we examined the relationship between participants' energy literacy scores and their performance on the task. Energy literacy was assessed using an 8-item questionnaire adapted from [@dewatersEnergyLiteracySecondary2011], which covers topics such as energy units, appliance energy consumption, and sources of electricity. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state: log_abs_error ~ els + (1|id) + (1|state). Results indicated a significant negative relationship between energy literacy and log absolute error (Estimate = -2.35, 95% CI: -2.88 to -1.81), suggesting that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (@fig-s1-els). \n\n\n\n## Experiment 1: Discussion\n\nExperiment 1 examined how different numerical representations of energy reduction goals affected participants’ planning accuracy. In line with our hypothesis that absolute units would yield better accuracy, the kWh condition supported significantly more precise energy reduction plans than did either the Percentage or USD conditions. Although the Percentage format was detrimental to accuracy relative to kWh, it was the USD condition that consistently produced the poorest outcomes, suggesting that monetary terms, while intuitive in everyday contexts, may not serve as effective reference classes for planning appliance-specific reductions in energy use.\n\nExperiment 2 will extend these findings by examining whether additional variables, such as the difficulty of the reduction goal or the rounding of numerical values, further interact with reference class conditions, thereby providing a more comprehensive understanding of how to optimize energy information presentation for improved planning accuracy.\n\n\n# Experiment 2\n\n\n## Methods\n\nThe experimental procedures in Experiment 2 are quite similar to those in Experiment 1. Experiment 2 employed a 2 (task goal: 10% vs. 15% reduction) x 2 (last year's usage: exact vs. rounded) within-subjects design, with a between-subjects manipulation of the reference class (USD vs. Percentage vs. kWh).. We recruited 206 participants from Amazon Mechanical Turk, but data from from 10 participants were corrupted due to experimenter error, leaving a final sample of 196 participants.\n\n\n\n## Results\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n\n::: {#tbl-s2-agg}\n\n|Reference Class |% meeting goal (exact) |% meeting goal (close match) |Abs. Deviation |Log Abs. Deviation |\n|:---------------|:----------------------|:----------------------------|:--------------|:------------------|\n|kWh             |0.44                   |0.52                         |0.02           |-3.9               |\n|Percentage      |0.28                   |0.42                         |0.06           |-3.2               |\n|USD             |0.20                   |0.29                         |0.10           |-2.4               |\n\nExperiment 2: Summary of planning accuracy by reference class. The table shows performance as both the % of trials where participants matched the goal, and the mean absolute error from the target reduction goal\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Study 1: Distribution of log absolute error by reference class. Displays the distributions of log absolute deviation from the target reduction goal across the three reference class conditions and is also faceted by calculator usage. Lower values indicate greater accuracy.](manuscript_files/figure-docx/fig-s2-log-dist-1.png){#fig-s2-log-dist}\n:::\n:::\n\n::: {#tbl-s2-ord .cell}\n\n:::\n\n\n\n\n\n\n\n\n\n::: {#tbl-s2-reg}\n|Parameter          |Estimate |CI_Lower |CI_Upper |pd   |\n|:------------------|:--------|:--------|:--------|:----|\n|Intercept[1]       |-1.45    |-2.85    |-0.07    |0.98 |\n|Intercept[2]       |1.26     |-0.09    |2.65     |0.97 |\n|refClassPercentage |1.02     |-0.63    |2.71     |0.89 |\n|refClassUSD        |2.27     |0.53     |3.98     |0.99 |\n|calcNoCalculator   |4.10     |2.20     |6.06     |1.00 |\n|pct_goal15%        |-0.39    |-0.81    |0.04     |0.96 |\n|roundedRounded     |-0.53    |-0.96    |-0.11    |0.99 |\n\n**Experiment 2.**  Parameter estimates from the ordinal regression model. Positive coefficients for refClass predictors indicate increased likelihood of falling into higher error categories relative to the kWh baseline.\n\n:::\n\n::: {#tbl-s2-ord}\n|comparison           |odds_ratio |ci_lower |ci_upper |\n|:--------------------|:----------|:--------|:--------|\n|Percentage vs kWh    |2.78       |0.53     |15.0     |\n|USD vs kWh           |9.68       |1.69     |53.4     |\n|calcNoCalculator     |60.37      |9.02     |426.4    |\n|15% Goal vs 10% Goal |0.68       |0.44     |1.0      |\n|Rounded vs Not       |0.59       |0.38     |0.9      |\n\n**Experiment 2.** Odds ratios for group comparisons. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the comparison condition.\n\n:::\n\n\n\n\n\n\nAs in Experiment 1, accuracy was categorized into three ordinal levels: \"Exact match\" (0% error), \"0.01-5% error,\" and \"Over 5% error\". The analyses for Experiment 2 employed a Bayesian ordinal regression model to examine the probability of falling into one of three accuracy categories (exact match, minor deviations, or substantial deviations) as a function of the reference class condition (kWh, Percentage, USD), while including pct_goal (10% vs. 15%), rounded (exact vs. rounded usage data), and calculator usage as additional predictors. Random intercepts were specified for both participant and state,\n\n\n\nThe ordinal regression analysis revealed that the USD reference class significantly increased the odds of higher error categories compared to the kWh reference class (OR = 9.68, 95% CI: [1.69, 53.4]). Participants in the USD condition were therefore substantially more likely to deviate from the target energy reduction goal compared to those in the kWh condition. In contrast, the Percentage condition’s odds ratio relative to kWh was more uncertain (OR = 2.78, 95% CI: 0.53, 15.0), indicating that although there may be a trend toward reduced accuracy in the Percentage condition, the evidence was not definitive.\n\nWe also found that using rounded numbers modestly improved accuracy (b = -0.53, 95% CI: [-0.96, -0.11]), with participants having 0.59 times the odds of falling into a worse accuracy category when working with rounded values. The more challenging 15% reduction goal was associated with slightly better performance compared to the 10% goal (b = -0.39, 95% CI: [-0.81, 0.04]), though this effect was relatively small. Consistent with Experiment 1, the use of a calculator had a large and significant effect on accuracy. The coefficient for calcNoCalculator was 4.10 (95% CI: 2.20, 6.06), and the corresponding odds ratio was 60.37 (95% CI: 9.02, 426.4), indicating that participants who did not use a calculator were substantially more likely to fall into higher error categories.\n\n\n@fig-s2-ame shows the marginal effects of refClass on each level of accuracy_level. These results reveal that switching from kWh to Percentage decreased the probability of an \"Exact match\" by an average of 7.0 percentage points (95% CI: -19.2, 4.2) and increased the probability of \"Over 5% error\" by 6.9 percentage points (95% CI: -4.5, 18.6). Similarly, switching from kWh to USD decreased the probability of an \"Exact match\" by 15 percentage points (95% CI: -26.7, -3.3) and increased the probability of \"Over 5% error\" by 16.5 percentage points (95% CI: 3.7, 29.3). \n\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Average marginal effects of reference class on accuracy levels (Experiment 2). The points represent the average change in the probability of each accuracy level when switching from the kWh reference class to Percentage (red) or USD (green). Error bars indicate 95% credible intervals. The results show that, compared to kWh, the Percentage format decreases the probability of an \"Exact match\" by 7.0% and increases the probability of \"Over 5% error\" by 6.9%. The USD format has a larger negative effect on \"Exact match\" (-14.7%) and a larger positive effect on \"Over 5% error\" (+16.5%). The effects on the \"0.01-5% error\" category are near zero for both comparisons.](manuscript_files/figure-docx/fig-s2-ame-1.png){#fig-s2-ame}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Posterior predictive check of the ordinal probit model, grouped by reference class (Experiment 2). The bars represent the observed proportions of each accuracy level within each reference class. The points represent the model's predicted proportions, with error bars indicating 95% credible intervals.](manuscript_files/figure-docx/fig-s2-ppd-1.png){#fig-s2-ppd}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Conditional effect of energy literacy on log absolute error. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.](manuscript_files/figure-docx/fig-s2-els-1.png){#fig-s2-els}\n:::\n:::\n\n\n\n\n\n\n\n\nWe once again examained the effect of energy literacy on planning accuracy. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state: log_abs_error ~ els + (1|id) + (1|state). This revealed a significant negative relationship between energy literacy and log absolute error (Estimate = -3.21, 95% CI: -3.89 to -2.52), indicating that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (@fig-s2-els).\n\n\n\n## Experiment 2: Discussion\n\n\nExperiment 2 built upon the findings of Experiment 1 by incorporating additional manipulations of goal difficulty (10% vs. 15% reduction) and numerical presentation (rounded vs. exact numbers), while maintaining the core manipulation of reference class (kWh, Percentage, USD). Nevertheless, the results largely converged with those of Experiment 1, providing further converging evidence that presenting energy reduction goals in absolute units (kWh) facilitates more accurate planning compared to percentage-based or monetary formats.\n\nTaken together, the results of Experiment 2 provide further support for the hypothesis that presenting energy reduction goals in absolute units (kWh) leads to more accurate planning compared to percentage-based or monetary formats. \n\nThe effect of goal difficulty, with the more challenging 15% reduction goal associated with slightly better performance, although counterintuitive, was nonetheless relatively small and may warrant further investigation in future research. The large and significant effect of calculator use, consistent across both experiments, underscores the crucial role of tools that individuals are likely to employ in real-world settings. Finally, the consistent relationship between energy literacy and accuracy, observed across both experiments, highlights the potential value of educational interventions aimed at improving consumers' understanding of energy concepts. \n\n\n\n\n\n\n\n# General Discusion\n\nAcross two experiments, we consistently found that presenting energy reduction goals in absolute units (kWh) led to more accurate planning compared to percentage-based or monetary representations. This advantage persisted across variations in goal difficulty and numerical presentation, suggesting a robust effect of reference class on planning accuracy.\n\n\nKarjalainen 2011 - people prefer information about price [@karjalainenConsumerPreferencesFeedback2011]\n\nMention @blaschBoundedlyRationalConsumers2019 - better long-term appliance selection with information presented in monetary terms. \n\n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# References\n::: {#refs}\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}