{
  "hash": "31bfabe0522caf6ff98fa17a6e6b62f0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Planning to Save Energy: How Information Format Affects Accuracy\"\naliases:\n  - /manuscript.html\nformat-links:   \n    - text: HTML\n      href: manuscript.html\n      icon: file-minus\n    - text: HTML (with code)\n      href: manuscript-code.html\n      icon: file-plus\n    - format: hikmah-manuscript-pdf\n      text: PDF version\n      icon: file-pdf\n    - docx\n    - gfm\ndate: 2025-01-09\nabstract: |\n    Effective communication of energy consumption information is crucial for promoting residential energy conservation. This study investigates how different numerical representations of energy reduction goals influence consumers' ability to create accurate conservation plans. Across two experiments, we examined the impact of presenting energy information in kilowatt-hours (kWh), percentages, or U.S. dollars (USD) on planning accuracy. Participants completed a simulated household planning task in which they allocated energy usage across multiple appliances, with the goal presented in either kilowatt-hours (kWh), percentages, or monetary costs. Results across both experiments showed that presenting reduction goals in absolute units (kWh) led to significantly greater accuracy compared to percentage-based or monetary formats. Furthermore, we found that higher energy literacy was associated with more accurate planning. These findings demonstrate that absolute units (kWh) are more effective for communicating energy-saving goals, and highlight the potential value of educational interventions to improve consumer energy literacy.\n---\n\n# Introduction\n\n### Literature Review\n\nEnergy costs often impose a significant burden on low-income households, leading to \"energy insecurity,\" where basic energy needs cannot be met (Bednar & Reames, 2020). Frequently measured as the energy burden—the percentage of income spent on energy bills—this burden can be disproportionately high for vulnerable families, necessitating difficult trade-offs with essentials such as food or medicine [@bednarRecognitionResponseEnergy2020; @memmottSociodemographicDisparitiesEnergy2021]. Energy insecurity has been linked to health risks and unsafe coping strategies, disproportionately impacting racial and ethnic minorities through higher rates of disconnection [@memmottSociodemographicDisparitiesEnergy2021]. While the broader context of climate change, partly driven by residential consumption [@farghaliStrategiesEnergyContext2023], underscores the need for sustainable solutions, the financial strain on vulnerable households remains a pressing concern. Promoting behavior change to reduce energy consumption is crucial. However, the success of such interventions may hinge on how effectively energy information is communicated, with format and presentation context significantly influencing understanding and action [@canfieldPerceptionsElectricityuseCommunications2017; @fischerFeedbackHouseholdElectricity2008].\n\n\nThe way numerical information is presented can significantly affect how individuals process and use that information. Of particular relevance are reference class effects, which occur when numerical statements are presented without a clear or intuitive basis for comparison, making it difficult to infer meaningful quantities[@gigerenzerSimpleToolsUnderstanding2003; @reimerNumericCommunicationRisk2015]. A substantial body of evidence suggests that presenting data in terms of absolute counts or frequencies, as opposed to probabilities or percentages, can promote more accurate comprehension and facilitate. However, it's important to note that even intuitive formats can pose challenges. For instance, @weberWhyCanOnly2018 found that individuals often struggle with reasoning tasks presented in natural frequencies because they inadvertently revert to more complex probabilistic thinking. \n\nThe choice of units and the format in which information is presented have also been shown to exert a significant influence on decision-making specifically within the context of energy consumption and planning.  For instance, tables are generally more effective than graphs for conveying specific electricity usage data because they facilitate straightforward point reading  @canfieldPerceptionsElectricityuseCommunications2017. Furthermore, the framing of energy costs, such as displaying monthly rather than daily or yearly expenses, can significantly affect consumers' choices [@gillConsumerMatchingCosts2022]. Consequently, the selection of an appropriate information format is crucial for effectively supporting energy-related decisions. Therefore, similar to natural frequencies, kWh provide a direct measure of energy use, a characteristic that could simplify calculations and facilitate comparisons, potentially helping consumers better understand and compare the energy consumption of different appliances or activities.  Conversely, prior research has suggested that consumers have a preference for receiving energy feedback in terms of monetary values over scientific units [@karjalainenConsumerPreferencesFeedback2011; @nematiImpactInformationbasedInterventions2020], as well as better long-term appliance selection with information presented in monetary terms [@blaschBoundedlyRationalConsumers2019]. However, it remains uncertain how these reported benefits might generalize to the more complex domain of household energy planning, where usage patterns can be multifaceted and subject to a variety of contextual influences.\n\nAlthough many individuals express a desire to conserve energy, research consistently shows that abstract goals (e.g., “reduce overall usage by 15%”) often fail to translate into effective behavior change unless accompanied by specific, actionable steps [@abrahamseReviewInterventionStudies2005; @nematiImpactInformationbasedInterventions2020]. For instance, @abrahamseReviewInterventionStudies2005 demonstrated that merely providing general information about energy savings rarely alters consumption patterns unless consumers also receive concrete instructions or tailored feedback. Similarly, @tonkeProvidingProceduralKnowledge2024 reported that sending households brief but precise text messages outlining how to reduce water use (e.g., limiting irrigation times, adjusting washing machine settings) yielded meaningful decreases in consumption, underscoring the importance of procedural knowledge—namely, knowing how to operationalize a goal rather than simply why it is desirable. In the context of energy conservation, this implies that interventions should not only highlight potential reductions (such as a 15% target) but also guide residents in allocating those reductions across specific appliances or behaviors [@attariPublicPerceptionsEnergy2010]. Additionally, meta-analytic findings suggest that people respond more robustly to household-level feedback that situates their usage within a personalized framework, thereby reducing the cognitive burden of figuring out next steps [@nematiImpactInformationbasedInterventions2020]. \n\nDespite existing studies on energy-use communication and format effects, limited research has explored how different numerical representations influence consumers' ability to create accurate energy conservation plans. Specifically, there is a gap in understanding how presenting energy information in absolute units versus percentages or monetary terms affects the precision of planning appliance-specific reductions. The current study addresses these critical issues by systematically investigating the impact of varying information formats (kWh, percentage, and USD) on the accuracy of energy-planning decisions. By manipulating the presentation format of energy information, this research aims to elucidate how different representational formats influence planning accuracy.Based on the literature reviewed, we hypothesize that: 1) Presenting energy reduction goals in absolute units (kWh) will lead to greater planning accuracy compared to percentage-based or monetary formats, as absolute units provide a more direct and less ambiguous representation of energy quantities. 2) Higher energy literacy will be associated with more accurate planning, as individuals with greater energy knowledge may be better equipped to process and utilize the provided information, regardless of format. We also examine the potential of several exploratory variables, such as goal difficulty and the rounding of numerical values, to further elucidate the factors that influence planning accuracy.\n\n\n\n# Experiment 1\n\nSee @fig-task for an example of a planning trial as it was seen by participants.\n\n## Methods\n\n### Participants\n\nWe implemented our task and surveys on Qualtrics, and recruited participants through Amazon Mechanical Turk. In Experiment 1, 252 participants were initially recruited. Data from 17 participants were corrupted due to experimenter error, and six participants were excluded due to deviant performance on the task, resulting in  a final sample of 229 participants (146 males, 92 females, 1 not specified). The average age of participants was 34.3 years (SD = 10.2). Most participants (76%) reported using a calculator to complete the task. \n\n### Materials and Design \n\nThe study employed a mixed design with reference class (kWh, percentage, USD) as a between-subjects factor and state/family scenario as a within-subjects factor. Each participant completed energy reduction planning tasks for two different states (i.e., family scenarios), with state order counterbalanced across participants. The family scenarios featured four households in different climate regions: Texas (Smith family) and California (Adams family) representing warm climates, and Colorado (Wells family) and Massachusetts (Davis family) representing cold climates. Average utility use data for each state was obtained from the  CITE SOURCE FOR STATE AVGS? Participants also completed an 8-item questionnaire assessing participants' knowledge of energy consumption and conversion [@dewatersEnergyLiteracySecondary2011], and a question indicating whether they used a calculator for the task. \n\n\n### Procedure\n\nParticipants were provided with energy usage data for two hypothetical families and tasked with creating action plans to meet specified energy reduction goals. These goals were implementing by allocating usage across five appliance categories: heating, cooling, water heating, refrigerator, and other appliances (e.g., TV, lighting). Participants were informed at the start of the task that they would be presented with tables of detailed energy usage data for each family, and that they would have to create 2 action plans for each of the families. Each action plan goal was implemented by allocating usage across five appliance categories: heating, cooling, water heating, refrigerator, and other appliances (e.g., TV, lighting, washer/dryer).For each family scenario, participants were shown a table containing the families utility usage from the prior year, alongside the state averages for each appliance category (see @fig-task). For each scenario, participants were asked to create two possible action plans to achieve the target reduction in total household energy usage . Depending on their reference class condition, the target reduction amount presented either in kilowatt-hours (kWh), as a percentage of total household usage, or in U.S. dollars. In all conditions, the target reduction was equivalent to a 15% reduction in total household kWh. \n\n\n![Example energy planning task trial. Participants saw a table with a family's previous year electricity usage (here for the Wells family in Colorado) and were asked to allocate energy usage to meet a 15% reduction goal. The format of the reduction goal was manipulated to be either a percentage (15% given as goal reduction), kilowatt hours (5965 kWh given), or USD (\\$656). Participants in the USD condition were provided with the conversion rate between kwH and USD.](/assets/images/Smith_10R_Wells_15E.png){#fig-task}\n\n\n\n\n## Results\n\n\n### Data Analysis\n\nAll preprocessing and analyses were carried out in R [@rcoreteamLanguageEnvironmentStatistical2020] and the tidyverse package [@wickhamWelcomeTidyverse2019]. Mixed Bayesian regressions were fit using the brms package [@burknerBrmsPackageBayesian2017], with participants and family scenario (states) set as random effects. \n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n::: {#tbl-s1-agg}\n\n|Reference Class |Avg. % Change |% meeting goal (exact) |% meeting goal (close match) |Abs. Deviation |Log Abs. Deviation |\n|:---------------|:-------------|:----------------------|:----------------------------|:--------------|:------------------|\n|kWh             |0.22          |0.38                   |0.54                         |0.03           |-3.7               |\n|Percentage      |0.21          |0.22                   |0.40                         |0.06           |-3.1               |\n|USD             |0.23          |0.10                   |0.22                         |0.10           |-2.4               |\n\nStudy 1: Summary of planning accuracy by reference class. The table shows performance as both the % of trials where participants matched the goal, and the mean absolute error from the target reduction goal\n\n:::\n\n@tbl-s1-agg that participants in the kWh condition met the target goal 38% of the time, compared to 22% for the Percentage condition and 10% for the USD condition. Moreover, the kWh reference class exhibited smaller deviations from the target reduction, suggesting that participants performed more accurately when the goal was framed in kWh rather than when percentages or USD.\n\n\nAs shown in @tbl-s1-agg, participants in the kWh condition exactly met the target reduction goal 38% of the time, significantly outperforming those in the Percentage (22%) and USD (10%) conditions. Furthermore, the kWh reference class exhibited notably smaller mean absolute deviations (0.03) compared to Percentage (0.06) and USD (0.10), suggesting that presenting the reduction goal in absolute units facilitated more precise allocations. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 1: Distribution of the log of the absolute error between the participant's action plan and the reduction goal across different reference class conditions (kWh, Percentage, USD). The right side plots are further separated by calculator usage. A lower log absolute error suggests higher planning accuracy.](manuscript_files/figure-pdf/fig-s1-log-dist-1.pdf){#fig-s1-log-dist}\n:::\n:::\n\n\n\n\n\n\n\n::: {#tbl-s1-prop .cell tbl-cap='Study 1: The table shows the percentage of participants who fell into each accuracy level for each reference class condition (percentages of kWh, $, and USD columns reflect within condition percentages). The combined group column reflects the percentage of participants in each accuracy level when aggregating across across all reference class conditions.'}\n::: {.cell-output-display}\n\n\n|Accuracy Level |kWh   |Percentage |USD   |Combined Groups % |\n|:--------------|:-----|:----------|:-----|:-----------------|\n|Exact match    |38.5% |22.4%      |10.2% |23.1%             |\n|0.01-5% error  |22.7% |29.5%      |25%   |25.5%             |\n|Over 5% error  |38.8% |48.1%      |64.8% |51.3%             |\n\n\n:::\n:::\n\n\n\n\n\n\nWe next categorized responses into three accuracy levels (exact match [0% error], minor deviations [0.01–5%], and large deviations [>5%]) for our primary statistical modeling. Using Bayesian ordinal regression, we modeled the ordered accuracy outcome as a function of the reference class condition, while controlling for random variation across participants and family scenarios:\n\n$$\n\\text{Accuracy Level} \\sim \\text{Reference Class} + \\text{Calculator} + (1|\\text{id}) + (1|\\text{Family Scenario})\n$$\n\n\nThis approach allowed us to estimate thresholds (intercepts) and regression coefficients that capture how different reference classes affect the likelihood of achieving higher accuracy categories. For each comparison, we provide posterior odds ratios (OR) and their 95% CIs. This approach allows the estimation of threshold parameters and regression coefficients that characterize how changes in predictor variables (such as the reference class: kWh, percentage, or USD) relate to probabilities of being in each accuracy category. Specifically, we used a cumulative logit link function to model the ordered accuracy outcome, and we specified weakly informative priors for the regression coefficients (normal distributions with mean 0 and standard deviation of 1) and for the cutpoints (normal distributions with a mean of zero and a standard deviation of 4.0). The approach allows us to estimate threshold parameters and regression coefficients that characterize how changes in predictor variables (such as the reference class: kWh, percentage, or USD) relate to probabilities of being in each accuracy category.\n\n\n::: {.cell}\n\n:::\n\n::: {#tbl-s1-reg}\n\n|Parameter          |Estimate |CI_Lower |CI_Upper |pd   |\n|:------------------|:--------|:--------|:--------|:----|\n|Intercept[1]       |-4.21    |-5.90    |-2.58    |1.00 |\n|Intercept[2]       |-0.89    |-2.49    |0.71     |0.87 |\n|refClassPercentage |1.44     |0.07     |2.88     |0.98 |\n|refClassUSD        |3.13     |1.81     |4.50     |1.00 |\n|calcUsedCalculator |-3.30    |-4.80    |-1.92    |1.00 |\n\n**Experiment 1**: Ordinal Regression results. Ordinal regression results. Positive coefficients for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline.\n\n:::\n\n::: {#tbl-s1-ord}\n|Comparison        |odds_ratio |ci_lower |ci_upper |\n|:-----------------|:----------|:--------|:--------|\n|Percentage vs kWh |4.2        |1.1      |18       |\n|USD vs kWh        |22.9       |6.1      |90       |\n\n\n**Experiment 1**: Odds ratios for group comparisons. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition.\n\n:::\n\n\nAs shown in @tbl-s1-reg, the reference class coefficients are positive for both the Percentage (Estimate = 1.3, 95% CI: 0.01 to 2.66, pd = 0.98) and USD (Estimate = 2.8, 95% CI: 1.52 to 4.04, pd = 1.00) conditions, relative to the kWh baseline. This indicates that, compared to the kWh condition, participants in both the Percentage and USD conditions were more likely to produce plans that fell into higher error categories. Moreover, the odds ratios (see Table 3) suggest that the USD condition led to a notably higher likelihood of large errors compared to the kWh baseline (OR = 15.7), while the Percentage condition also demonstrated increased odds (OR = 3.7) but was somewhat less detrimental to accuracy than USD. These results align with our descriptive findings and further clarify that framing the target reductions in absolute kWh units may facilitate significantly more accurate planning. Posterior predictive checks showed that the ordinal model provided a reasonable fit to the observed data (see @fig-s1-ppd).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 1: Posterior predictive check for frequency of trials at each accuracy level, faceted by reference class (kWh, Percentage, USD). Bars show observed, dots show model predicted proportions. Better accuracy is indicated by higher proportions in the 'Exact Match' and '0.01-5% error' categories.](manuscript_files/figure-pdf/fig-s1-ppd-1.pdf){#fig-s1-ppd}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 1. Conditional effect of energy literacy on log absolute error. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.](manuscript_files/figure-pdf/fig-s1-els-1.pdf){#fig-s1-els}\n:::\n:::\n\n\nTo further investigate individual factors that may influence planning accuracy, we examined the relationship between participants' energy literacy scores and their performance on the task. Energy literacy was assessed using an 8-item questionnaire adapted from [@dewatersEnergyLiteracySecondary2011], which covers topics such as energy units, appliance energy consumption, and sources of electricity. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state: log_abs_error ~ els + (1|id) + (1|state). Results indicated a significant negative relationship between energy literacy and log absolute error (Estimate = -2.35, 95% CI: -2.88 to -1.81), suggesting that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (@fig-s1-els). \n\n\n\n## Experiment 1: Discussion\n\nExperiment 1 examined how different numerical representations of energy reduction goals affected participants’ planning accuracy. In line with our hypothesis that absolute units would yield better accuracy, the kWh condition supported significantly more precise energy reduction plans than did either the Percentage or USD conditions. Although the Percentage format was detrimental to accuracy relative to kWh, it was the USD condition that consistently produced the poorest outcomes, suggesting that monetary terms, while intuitive in everyday contexts, may not serve as effective reference classes for planning appliance-specific reductions in energy use.\n\nExperiment 2 will extend these findings by examining whether additional variables, such as the difficulty of the reduction goal or the rounding of numerical values, further interact with reference class conditions, thereby providing a more comprehensive understanding of how to optimize energy information presentation for improved planning accuracy.\n\n\n# Experiment 2\n\n\n## Methods\n\nIn Experiment 2, We recruited 206 participants from Amazon Mechanical Turk, but data from from 10 participants were corrupted due to experimenter error, and six excluded due to deviant behavior, leaving a final sample of 190 participants (102 male; 88 female. Average age = 35.5, SD=9.5)\n\nExperiment 2 employed a mixed experimental design with reference class (USD, Percentage, kWh) as a between-subjects factor,  and two within-subjects factors: task goal (10% vs. 15% reduction) and the presentation of last year's usage data (exact vs. rounded numbers). The order of presentation of the goal, rounding, and state conditions was counterbalanced across participants.  As in Experiment 1, each participant completed the energy reduction planning task for two different family-state scenarios. In the “rounded” condition, both the family’s previous year usage and the state averages were rounded to the nearest whole number.\n\n\n\n## Results\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {#tbl-s2-agg}\n\n|Reference Class |% meeting goal (exact) |% meeting goal (close match) |Abs. Deviation |Log Abs. Deviation |\n|:---------------|:----------------------|:----------------------------|:--------------|:------------------|\n|kWh             |0.44                   |0.52                         |0.02           |-3.9               |\n|Percentage      |0.28                   |0.42                         |0.06           |-3.2               |\n|USD             |0.20                   |0.29                         |0.10           |-2.4               |\n\nExperiment 2: Summary of planning accuracy by reference class. The table shows performance as both the % of trials where participants matched the goal, and the mean absolute error from the target reduction goal\n\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2: Distribution of the log of the absolute error between the participant's action plan and the reduction goal across different reference class conditions (kWh, Percentage, USD). The right side plots are further separated by calculator usage. A lower log absolute error suggests higher planning accuracy.](manuscript_files/figure-pdf/fig-s2-log-dist-1.pdf){#fig-s2-log-dist}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n::: {#tbl-s2-ord .cell}\n\n:::\n\n\n::: {#tbl-s2-reg}\n|Parameter          |Estimate |CI_Lower |CI_Upper |pd   |\n|:------------------|:--------|:--------|:--------|:----|\n|Intercept[1]       |-1.45    |-2.85    |-0.07    |0.98 |\n|Intercept[2]       |1.26     |-0.09    |2.65     |0.97 |\n|refClassPercentage |1.02     |-0.63    |2.71     |0.89 |\n|refClassUSD        |2.27     |0.53     |3.98     |0.99 |\n|calcNoCalculator   |4.10     |2.20     |6.06     |1.00 |\n|pct_goal15%        |-0.39    |-0.81    |0.04     |0.96 |\n|roundedRounded     |-0.53    |-0.96    |-0.11    |0.99 |\n\n**Experiment 2.**  Parameter estimates from the ordinal regression model. Positive coefficients for refClass predictors indicate increased likelihood of falling into higher error categories relative to the kWh baseline.\n\n:::\n\n::: {#tbl-s2-ord}\n|comparison           |odds_ratio |ci_lower |ci_upper |\n|:--------------------|:----------|:--------|:--------|\n|Percentage vs kWh    |2.78       |0.53     |15.0     |\n|USD vs kWh           |9.68       |1.69     |53.4     |\n|calcNoCalculator     |60.37      |9.02     |426.4    |\n|15% Goal vs 10% Goal |0.68       |0.44     |1.0      |\n|Rounded vs Not       |0.59       |0.38     |0.9      |\n\n**Experiment 2.** Odds ratios for group comparisons. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the comparison condition.\n\n:::\n\n\n\nAs in Experiment 1, accuracy was categorized into three ordinal levels: \"Exact match\" (0% error), \"0.01-5% error,\" and \"Over 5% error\". The analyses for Experiment 2 employed a Bayesian ordinal regression model to examine the probability of falling into one of three accuracy categories (exact match, minor deviations, or substantial deviations) as a function of the reference class condition (kWh, Percentage, USD), while including pct_goal (10% vs. 15%), rounded (exact vs. rounded usage data), and calculator usage as additional predictors. Random intercepts were specified for both participant and state,\n\nThe ordinal regression analysis revealed that the USD reference class significantly increased the odds of higher error categories compared to the kWh reference class (OR = 9.68, 95% CI: [1.69, 53.4]). Participants in the USD condition were therefore substantially more likely to deviate from the target energy reduction goal compared to those in the kWh condition. In contrast, the Percentage condition’s odds ratio relative to kWh was more uncertain (OR = 2.78, 95% CI: 0.53, 15.0), indicating that although there may be a trend toward reduced accuracy in the Percentage condition, the evidence was not definitive.\n\nWe also found that using rounded numbers modestly improved accuracy (b = -0.53, 95% CI: [-0.96, -0.11]), with participants having 0.59 times the odds of falling into a worse accuracy category when working with rounded values. The more challenging 15% reduction goal was associated with slightly better performance compared to the 10% goal (b = -0.39, 95% CI: [-0.81, 0.04]), though this effect was relatively small. Consistent with Experiment 1, the use of a calculator had a large and significant effect on accuracy. The coefficient for calcNoCalculator was 4.10 (95% CI: 2.20, 6.06), and the corresponding odds ratio was 60.37 (95% CI: 9.02, 426.4), indicating that participants who did not use a calculator were substantially more likely to fall into higher error categories.\n\n\n@fig-s2-ame shows the marginal effects of refClass on each level of accuracy_level. These results reveal that switching from kWh to Percentage decreased the probability of an \"Exact match\" by an average of 7.0 percentage points (95% CI: -19.2, 4.2) and increased the probability of \"Over 5% error\" by 6.9 percentage points (95% CI: -4.5, 18.6). Similarly, switching from kWh to USD decreased the probability of an \"Exact match\" by 15 percentage points (95% CI: -26.7, -3.3) and increased the probability of \"Over 5% error\" by 16.5 percentage points (95% CI: 3.7, 29.3). \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Average marginal effects of reference class on accuracy levels (Experiment 2). The points represent the average change in the probability of each accuracy level when switching from the kWh reference class to Percentage (red) or USD (green). Error bars indicate 95% credible intervals. The results show that, compared to kWh, the Percentage format decreases the probability of an \"Exact match\" by 7.0% and increases the probability of \"Over 5% error\" by 6.9%. The USD format has a larger negative effect on \"Exact match\" (-14.7%) and a larger positive effect on \"Over 5% error\" (+16.5%). The effects on the \"0.01-5% error\" category are near zero for both comparisons.](manuscript_files/figure-pdf/fig-s2-ame-1.pdf){#fig-s2-ame}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Posterior predictive check of the bayesian regression model, faceted by reference class. The bars represent the observed frequencies of each accuracy level within each reference class. The points represent the model's predicted proportions, with error bars indicating 95% credible intervals.](manuscript_files/figure-pdf/fig-s2-ppd-1.pdf){#fig-s2-ppd}\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Experiment 2. Conditional effect of energy literacy on log absolute error. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.](manuscript_files/figure-pdf/fig-s2-els-1.pdf){#fig-s2-els}\n:::\n:::\n\nWe once again examined the effect of energy literacy on planning accuracy. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state: log_abs_error ~ els + (1|id) + (1|state). This revealed a significant negative relationship between energy literacy and log absolute error (Estimate = -3.21, 95% CI: -3.89 to -2.52), indicating that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (@fig-s2-els).\n\n\n## Experiment 2: Discussion\n\nExperiment 2 aimed to build upon the findings of Experiment 1 by replicating the core manipulation of reference class. Additionally, it incorporated variables that might influence planning accuracy. These included goal difficulty and the way that the prior year's usage was presented (rounded or exact). The results largely converged with those of Experiment 1, providing further converging evidence that presenting energy reduction goals in absolute units (kWh) facilitates more accurate planning compared to percentage-based or monetary formats.\n\nTaken together, the results of Experiment 2 provide further support for the hypothesis that presenting energy reduction goals in absolute units (kWh) leads to more accurate planning compared to percentage-based or monetary formats. \n\nThe finding that the more challenging 15% reduction goal was associated with a slight improvement in accuracy is counterintuitive. It may be that participants put more effort into the task under this condition, or perhaps this is an artifact of the way that the task was presented. However, this effect was relatively small and thus should be explored in future research to better understand its underlying mechanisms. Furthermore, the magnitude of the effect size of this manipulation should be examined to better understand the practical implications of goal difficulty for energy conservation. \n\nThe large and significant effect of calculator use, consistent across both experiments, underscores the crucial role of tools that individuals are likely to employ in real-world settings. Finally, the consistent relationship between energy literacy and accuracy, observed across both experiments, highlights the potential value of educational interventions aimed at improving consumers' understanding of energy concepts. \n\n\n# General Discussion\n\n\nThis study examined how different numerical representations of energy reduction goals influence consumers’ ability to create accurate energy conservation plans. Across two experiments, the findings consistently demonstrated that presenting reduction goals in absolute units (kWh) significantly enhanced planning accuracy compared to percentage-based or monetary formats. Furthermore, participants with higher energy literacy exhibited more precise planning across all conditions, underscoring the critical role of domain-specific knowledge in shaping decision-making outcomes.\n\nThese results align with the broader literature on numerical cognition, which suggests that the format in which information is presented can profoundly affect comprehension and decision-making  [@gigerenzerSimpleToolsUnderstanding2003; @reimerNumericCommunicationRisk2015]. However, our study extends beyond simple estimations or judgments, demonstrating that the advantages of absolute units persist even in a more complex, multi-step planning task. Moreover, the consistent superiority of kWh over both percentages and USD provides novel insights into the specific challenges of energy-related decision-making. While prior research has suggested that consumers may prefer monetary feedback [@karjalainenConsumerPreferencesFeedback2011; @nematiImpactInformationbasedInterventions2020] or that monetary framing can improve long-term appliance choices [@blaschBoundedlyRationalConsumers2019], our findings indicate that when it comes to allocating specific usage reductions across appliances, absolute units are most effective. This may be because kWh provide a more direct and less ambiguous representation of energy quantities, facilitating the necessary calculations for accurate planning. Nevertheless, it is unclear whether the observed benefits of absolute units (i.e., kWh) are genuinely attributable to their absolute nature, or if other inherent characteristics of these units might be driving the effects. \nFurthermore, the percentage-based reduction targets, while potentially more salient from a goal-setting perspective, also resulted in poorer planning outcomes compared to kWh. Such a finding suggests that reliance on percentages can further complicate calculations by adding unnecessary transformations in the problem-solving process, in line with the \"off by 100% bias\" found in @fisher100BiasEffects2022, where they show that individuals often misunderstand percentage changes greater than 100%. The relative ease in using absolute values to arrive at an accurate plan suggests that these representations of the planning task result in the most accurate planning strategies because the number of steps required to perform the required calculations are simpler.\n\nMoreover, the consistent positive relationship observed between energy literacy and planning accuracy across both experiments underscores the importance of baseline knowledge in effectively navigating energy-related information. Individuals with higher levels of energy literacy demonstrated a greater capacity to formulate accurate conservation plans, irrespective of the information format presented. This finding aligns with previous research highlighting the role of numeracy and domain-specific knowledge in improving judgments related to energy consumption [@attariPublicPerceptionsEnergy2010]. It further suggests that interventions aimed at enhancing consumers' fundamental understanding of energy concepts could yield significant benefits in improving the effectiveness of energy conservation efforts.\n\n\n\n## Limitations\n\n- Each participant only completed 4 action plans\n- calculator use not controlled. \n\n\n\n\n\n-----\n\n\nStorage/GoogleDrive-tegorman13@gmail.com/My%20Drive/Purdue/Representation_Study/manuscript/output/appendix.html\n\nSupplementary information and materials can be found online at [this website](https://tegorman13.github.io/Representation_Study/docs/manuscript/output/apendix.html)\n\n{{< pagebreak >}}\n\n# References\n::: {#refs}\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}