<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.20">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thomas E. Gorman">
<meta name="author" content="Torsten Reimer">
<meta name="author" content="Juan Pablo Loaiza Ramirez">
<meta name="author" content="Hayden Barber">
<meta name="dcterms.date" content="2025-03-31">
<meta name="keywords" content="energy literacy, information format, planning accuracy, decision making">
<meta name="description" content="PLANNING TO SAVE ENERGY: HOW INFORMATION FORMAT AFFECTS ACCURACY">

<title>Planning to Save Energy: How Information Format Affects Accuracy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-6bb072e51ab976e338d8fd19b221fbe5.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-c8e4cb88a0b19d08ea814c32ad428d8c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner {
        background: #000D51;
      }
</style>
<style type="text/css">
h2.hide {
    display: none;
}
</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#experiment-1" id="toc-experiment-1" class="nav-link" data-scroll-target="#experiment-1">Experiment 1</a>
  <ul class="collapse">
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#experiment-1-discussion" id="toc-experiment-1-discussion" class="nav-link" data-scroll-target="#experiment-1-discussion">Experiment 1: Discussion</a></li>
  </ul></li>
  <li><a href="#experiment-2" id="toc-experiment-2" class="nav-link" data-scroll-target="#experiment-2">Experiment 2</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#methods-1" id="toc-methods-1" class="nav-link" data-scroll-target="#methods-1">Methods</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#experiment-2-discussion" id="toc-experiment-2-discussion" class="nav-link" data-scroll-target="#experiment-2-discussion">Experiment 2: Discussion</a></li>
  </ul></li>
  <li><a href="#general-discussion" id="toc-general-discussion" class="nav-link" data-scroll-target="#general-discussion">General Discussion</a>
  <ul class="collapse">
  <li><a href="#limitations-and-future-directions" id="toc-limitations-and-future-directions" class="nav-link" data-scroll-target="#limitations-and-future-directions">Limitations and Future Directions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript.html"><i class="bi bi-file-minus"></i>HTML</a></li><li><a href="manuscript-code.html"><i class="bi bi-file-plus"></i>HTML (with code)</a></li><li><a href="rs_manuscript_apa.pdf"><i class="bi bi-file-pdf"></i>PDF version (apaquarto)</a></li><li><a href="rs_manuscript_apa.docx"><i class="bi bi-file-word"></i>docx</a></li><li><a href="manuscript_gfm.md"><i class="bi bi-file-code"></i>Github (GFM)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<br>

<br>

<section id="title" class="level2 title unnumbered unlisted">
<h2 class="title unnumbered unlisted" data-anchor-id="title">Planning to Save Energy: How Information Format Affects Accuracy</h2>
<div class="Author">
<br>

<p>Thomas E. Gorman<sup>1,2</sup>, Torsten Reimer<sup>1,2</sup>, Juan Pablo Loaiza Ramirez<sup>1,2</sup>, and Hayden Barber<sup>3</sup></p>
<p><sup>1</sup>Communication and Cognition Lab, Purdue University</p>
<p><sup>2</sup>Purdue University, College of Liberal Arts Research Academy</p>
<p><sup>3</sup>School of Communication &amp; Journalism, South Dakota State University</p>
</div>
</section>
<section id="author-note" class="level2 unnumbered unlisted AuthorNote">
<h2 class="unnumbered unlisted AuthorNote" data-anchor-id="author-note">Author Note</h2>
</section>
<section id="abstract" class="level2 unnumbered unlisted AuthorNote">
<h2 class="unnumbered unlisted AuthorNote" data-anchor-id="abstract">Abstract</h2>
<div class="AbstractFirstParagraph">
<p>Effective communication of energy consumption information is crucial for promoting residential energy conservation. This study investigates how different numerical representations of energy reduction goals influence consumers’ ability to create accurate conservation plans. Across two experiments, we examined the impact of presenting energy information in kilowatt-hours (kWh), percentages, or U.S. dollars (USD) on planning accuracy. Participants completed a simulated household planning task in which they allocated energy usage across multiple appliances, with the goal presented in either kilowatt-hours (kWh), percentages, or monetary costs. Results across both experiments showed that presenting reduction goals in absolute units (kWh) led to significantly greater accuracy compared to percentage-based or monetary formats. Furthermore, we found that higher energy literacy was associated with more accurate planning. These findings demonstrate that absolute units (kWh) are more effective for communicating energy-saving goals, and highlight the potential value of educational interventions to improve consumer energy literacy.</p>
</div>
<p><em>Keywords</em>: energy literacy, information format, planning accuracy, decision making</p>
</section>
<section id="firstheader" class="level2 title unnumbered unlisted">
<h2 class="title unnumbered unlisted" data-anchor-id="firstheader">Planning to Save Energy: How Information Format Affects Accuracy</h2>
</section>
<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">Introduction</h2>
<p>Energy insecurity has emerged as a critical public health concern, especially among low-income households, who frequently face difficult choices between paying energy bills and meeting other essential needs <span class="citation" data-cites="bednarRecognitionResponseEnergy2020 memmottSociodemographicDisparitiesEnergy2021">(<a href="#ref-bednarRecognitionResponseEnergy2020" role="doc-biblioref">Bednar &amp; Reames, 2020</a>; <a href="#ref-memmottSociodemographicDisparitiesEnergy2021" role="doc-biblioref">Memmott et al., 2021</a>)</span>. Such households often experience unsafe coping strategies (e.g., foregoing heating during winter months), which disproportionately affect at-risk populations and heighten risks of utility disconnection <span class="citation" data-cites="memmottSociodemographicDisparitiesEnergy2021">(<a href="#ref-memmottSociodemographicDisparitiesEnergy2021" role="doc-biblioref">Memmott et al., 2021</a>)</span>. Moreover, residential energy use contributes to climate change, intensifying the urgency for sustainable solutions <span class="citation" data-cites="farghaliStrategiesEnergyContext2023">(<a href="#ref-farghaliStrategiesEnergyContext2023" role="doc-biblioref">Farghali et al., 2023</a>)</span>.</p>
<p>Given the relevance of promoting behavior change to reduce energy consumption, several strands of research have aimed to identify factors that affect energy behaviors and interventions that effectively reduce energy consumption. For example, <span class="citation" data-cites="abrahamseEffectTailoredInformation2007">Abrahamse et al. (<a href="#ref-abrahamseEffectTailoredInformation2007" role="doc-biblioref">2007</a>)</span> used a combination of tailored information about energy use and tailored feedback, in addition to setting an energy-saving goal, to promote direct and indirect energy-saving behaviors and high levels of knowledge regarding energy use. Direct energy-saving behaviors were classified as reducing fuel, gas, and electricity consumption, while indirect behaviors referred to producing, distributing, and disposing goods. After a five-month intervention, the authors found that households in the experimental group reduced their direct energy use by 5.1% and had higher levels of knowledge about energy conservation compared to the control group, which used 0.7% more energy since the beginning of the intervention. No difference between groups was found in indirect behaviors.</p>
<p>However, the success of such interventions may hinge on how effectively energy information is communicated, with format and presentation context significantly influencing understanding and action <span class="citation" data-cites="canfieldPerceptionsElectricityuseCommunications2017 fischerFeedbackHouseholdElectricity2008">(<a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">Canfield et al., 2017</a>; <a href="#ref-fischerFeedbackHouseholdElectricity2008" role="doc-biblioref">Fischer, 2008</a>)</span>. Consequently, a pressing challenge lies in designing communication strategies that effectively convey energy data and motivate practical conservation decisions. We set out to explore whether consumers are able to develop plans that would help meet certain energy consumption goals.</p>
<section id="representation-formats" class="level4">
<h4 data-anchor-id="representation-formats">Representation Formats</h4>
<p>Receiving feedback about one’s energy use is important in identifying potential actions to reduce energy consumption. However, it is crucial to understand how consumers use the information provided with their energy bill and whether they are able to translate an energy-saving goal into an action plan. <span class="citation" data-cites="canfieldPerceptionsElectricityuseCommunications2017">Canfield et al. (<a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">2017</a>)</span> specifically studied this problem by running an experiment in which participants were shown hypothetical electricity bills with information related to a household’s historical electricity use, electricity use in relation to their neighbors, and historical electricity use by appliances. Participants were randomly assigned to one of three formats of information representation (i.e., tables, bar graphs, and icon graphs) and were asked questions regarding their energy literacy. <span class="citation" data-cites="canfieldPerceptionsElectricityuseCommunications2017">Canfield et al. (<a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">2017</a>)</span> showed that tables were the easiest format to understand for consumers when evaluating every type of information related to energy use. Across types of information, historical electricity use elicited the highest intentions and preferences for energy savings regardless of format. Additionally, participants with high energy literacy had a better understanding of energy-related information across all types of information representations. Studies such as <span class="citation" data-cites="dewatersEnergyLiteracySecondary2011">DeWaters and Powers (<a href="#ref-dewatersEnergyLiteracySecondary2011" role="doc-biblioref">2011</a>)</span> have highlighted that while individuals may express concern for energy issues, their actual knowledge and behaviors may not align, underscoring the importance of fostering a comprehensive understanding of energy concepts to facilitate effective conservation actions. By disentangling the effects of content, format, and individual differences in energy literacy on understanding, preferences, and intentions, <span class="citation" data-cites="canfieldPerceptionsElectricityuseCommunications2017">Canfield et al. (<a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">2017</a>)</span> demonstrated that easy-to-implement communication strategies in energy bills can lead to energy-saving behaviors.</p>
<p>Although many individuals express a desire to conserve energy, research consistently shows that abstract goals (e.g., “reduce overall usage by 15%”) often fail to translate into effective behavior change unless accompanied by specific, actionable steps <span class="citation" data-cites="abrahamseReviewInterventionStudies2005 nematiImpactInformationbasedInterventions2020">(<a href="#ref-abrahamseReviewInterventionStudies2005" role="doc-biblioref">Abrahamse et al., 2005</a>; <a href="#ref-nematiImpactInformationbasedInterventions2020" role="doc-biblioref">Nemati &amp; Penn, 2020</a>)</span>. For instance, <span class="citation" data-cites="abrahamseReviewInterventionStudies2005">Abrahamse et al. (<a href="#ref-abrahamseReviewInterventionStudies2005" role="doc-biblioref">2005</a>)</span> demonstrated that merely providing general information about energy savings rarely alters consumption patterns unless consumers also receive concrete instructions or tailored feedback.</p>
<p>Similarly, <span class="citation" data-cites="tonkeProvidingProceduralKnowledge2024">Tonke (<a href="#ref-tonkeProvidingProceduralKnowledge2024" role="doc-biblioref">2024</a>)</span> reported that sending households brief but precise text messages outlining how to reduce water use (e.g., limiting irrigation times, adjusting washing machine settings) yielded meaningful decreases in consumption, underscoring the importance of procedural knowledge—namely, knowing how to operationalize a goal rather than simply why it is desirable. In the context of energy conservation, this implies that interventions should not only highlight potential reductions (such as a 15% target) but also guide residents in allocating those reductions across specific appliances or behaviors <span class="citation" data-cites="attariPublicPerceptionsEnergy2010">(<a href="#ref-attariPublicPerceptionsEnergy2010" role="doc-biblioref">Attari et al., 2010</a>)</span>. Additionally, meta-analytic findings suggest that people respond more robustly to household-level feedback that situates their usage within a personalized framework, thereby reducing the cognitive burden of determining next steps <span class="citation" data-cites="nematiImpactInformationbasedInterventions2020">(<a href="#ref-nematiImpactInformationbasedInterventions2020" role="doc-biblioref">Nemati &amp; Penn, 2020</a>)</span>.</p>
<p>The way numerical information is presented can significantly affect how individuals process and use that information. Of particular relevance are reference class effects, which occur when numerical statements are presented without a clear or intuitive basis for comparison, making it difficult to infer meaningful quantities <span class="citation" data-cites="gigerenzerSimpleToolsUnderstanding2003 reimerNumericCommunicationRisk2015">(<a href="#ref-gigerenzerSimpleToolsUnderstanding2003" role="doc-biblioref">Gigerenzer &amp; Edwards, 2003</a>; <a href="#ref-reimerNumericCommunicationRisk2015" role="doc-biblioref">Reimer et al., 2015</a>)</span>. A substantial body of evidence suggests that presenting data in terms of absolute counts or frequencies, as opposed to probabilities or percentages, can promote more accurate comprehension and facilitate decision making. However, it is important to note that even intuitive formats can pose challenges. For instance, <span class="citation" data-cites="weberWhyCanOnly2018">Weber et al. (<a href="#ref-weberWhyCanOnly2018" role="doc-biblioref">2018</a>)</span> found that individuals often struggle with reasoning tasks presented in natural frequencies because they inadvertently revert to more complex probabilistic thinking.</p>
<p>The choice of units and the format in which information is presented have also been shown to exert a significant influence on decision-making within the context of energy consumption and planning. For instance, tables are generally more effective than graphs for conveying specific electricity usage data because they facilitate straightforward point reading <span class="citation" data-cites="canfieldPerceptionsElectricityuseCommunications2017">(<a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">Canfield et al., 2017</a>)</span>. Furthermore, the framing of energy costs, such as displaying monthly rather than daily or yearly expenses, can significantly affect consumers’ choices <span class="citation" data-cites="gillConsumerMatchingCosts2022">(<a href="#ref-gillConsumerMatchingCosts2022" role="doc-biblioref">Gill et al., 2022</a>)</span>. Consequently, the selection of an appropriate information format is crucial for effectively supporting energy-related decisions. Therefore, similar to natural frequencies, kWh provide a direct measure of energy use - a characteristic that could simplify calculations and facilitate comparisons, potentially helping consumers better understand and compare the energy consumption of different appliances or activities. Conversely, prior research has suggested that consumers have a preference for receiving energy feedback in terms of monetary values over scientific units <span class="citation" data-cites="karjalainenConsumerPreferencesFeedback2011 nematiImpactInformationbasedInterventions2020">(<a href="#ref-karjalainenConsumerPreferencesFeedback2011" role="doc-biblioref">Karjalainen, 2011</a>; <a href="#ref-nematiImpactInformationbasedInterventions2020" role="doc-biblioref">Nemati &amp; Penn, 2020</a>)</span>, as well as better long-term appliance selection with information presented in monetary terms <span class="citation" data-cites="blaschBoundedlyRationalConsumers2019">(<a href="#ref-blaschBoundedlyRationalConsumers2019" role="doc-biblioref">Blasch et al., 2019</a>)</span>. However, it remains uncertain how these reported benefits might generalize to the more complex task of household energy planning, where usage patterns are multifaceted and subject to a variety of contextual influences.</p>
</section>
<section id="overview-of-current-research" class="level4">
<h4 data-anchor-id="overview-of-current-research">Overview of Current Research</h4>
<p>Despite existing studies on energy-use communication and format effects, limited research has explored how different numerical representations influence consumers’ ability to create accurate energy conservation plans. Specifically, there is a gap in understanding how presenting energy information in absolute units versus percentages or monetary terms affects the precision of planning appliance-specific reductions. The current study addresses these critical issues by systematically investigating the impact of varying information formats (kWh, percentage, and USD) on the accuracy of energy-planning decisions. By manipulating the presentation format of energy information, this research aims to elucidate how different representational formats influence planning accuracy. Based on the literature reviewed, we hypothesized that: 1) Presenting energy reduction goals in absolute units (kWh) will lead to greater planning accuracy compared to percentage-based or monetary formats, as absolute units provide a more direct and less ambiguous representation of energy quantities. 2) Higher energy literacy will be associated with more accurate planning, as individuals with greater energy knowledge may be better equipped to process and utilize the provided information, regardless of format. We also examined the potential of several exploratory variables, such as goal difficulty and the rounding of numerical values, to further elucidate the factors that influence planning accuracy.</p>
</section>
</section>
<section id="experiment-1" class="level2">
<h2 data-anchor-id="experiment-1">Experiment 1</h2>
<p>See <a href="#fig-task" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> for an example of a planning trial as it was seen by participants.</p>
<section id="methods" class="level3">
<h3 data-anchor-id="methods">Methods</h3>
<section id="participants" class="level4">
<h4 data-anchor-id="participants">Participants</h4>
<p>We implemented our task and surveys on Qualtrics, and recruited participants through Amazon Mechanical Turk. In Experiment 1, 235 participants were initially recruited. Data from six participants were excluded due to unusually large error magnitudes (error magnitudes exceeding 2.5 standard deviations from the group mean), resulting in a final sample of 229 participants (136 males, 92 females, 1 participant not specified). The average age of participants was 34.3 years (SD = 10.2). Most participants (76%) reported using a calculator to complete the task.</p>
</section>
<section id="materials-and-design" class="level4">
<h4 data-anchor-id="materials-and-design">Materials and Design</h4>
<p>The study employed a mixed design with reference class (kWh, percentage, USD) as a between-subjects factor and state/family scenario as a within-subjects factor. Each participant completed energy reduction planning tasks for two different states (i.e., family scenarios), with state order counterbalanced across participants. The family scenarios featured four households in different climate regions: Texas (Smith family) and California (Adams family) representing warm climates, and Colorado (Wells family) and Massachusetts (Davis family) representing cold climates. Participants also completed an 8-item questionnaire assessing their knowledge of energy consumption and conversion <span class="citation" data-cites="dewatersEnergyLiteracySecondary2011">(<a href="#ref-dewatersEnergyLiteracySecondary2011" role="doc-biblioref">DeWaters &amp; Powers, 2011</a>)</span>, and a question indicating whether they used a calculator for the task.</p>
</section>
<section id="procedure" class="level4">
<h4 data-anchor-id="procedure">Procedure</h4>
<p>Participants were provided with energy usage data for two hypothetical families and tasked with creating action plans to meet specified energy reduction goals. Participants were informed at the start of the study that they would be presented with tables of detailed energy usage data for each family, and that they would have to create 2 action plans for each of the families. Each action plan goal was implemented by allocating usage across five appliance categories: heating, cooling, water heating, refrigerator, and other appliances (e.g., TV, lighting, washer/dryer). For each family scenario, participants were shown a table containing the family’s utility usage from the prior year, alongside the state averages for each appliance category (see <a href="#fig-task" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a>). For each scenario, participants were asked to create two possible action plans to achieve the target reduction in total household energy usage . Depending on their reference class condition, the target reduction amount was presented either in kilowatt-hours (kWh), as a percentage of total household usage, or in U.S. dollars. In all conditions, the target reduction was equivalent to a 15% reduction in total household kWh. For example, participants assigned to the Wells family scenario (Colorado), as depicted in Figure 1, were asked to achieve a reduction of 5,965 kWh in the kWh condition, 15% in the Percentage condition, or $656 in the USD condition, all representing the same underlying 15% energy reduction target for that specific household.</p>
<div id="fig-task" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" prefix="" data-fignum="1" data-apa-note="Participants saw a table with a family's previous year electricity usage (here for the Wells family in Colorado) and were asked to allocate energy usage to meet a 15% reduction goal. The format of the reduction goal was manipulated to be either a percentage (15% reduction), kilowatt hours (5965 kWh), or USD ($656). Participants in the USD condition were provided with the conversion rate between kWh and USD. All participants completed two scenarios, and for each scenario, they proposed two distinct action plans" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-task-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Example energy planning task trial</p>
</div>
</figcaption>
<div aria-describedby="fig-task-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./assets/images/wells10e_pub.png" class="img-fluid figure-img" style="width:80.0%" data-apa-note="Participants saw a table with a family's previous year electricity usage (here for the Wells family in Colorado) and were asked to allocate energy usage to meet a 15% reduction goal. The format of the reduction goal was manipulated to be either a percentage (15% reduction), kilowatt hours (5965 kWh), or USD ($656). Participants in the USD condition were provided with the conversion rate between kWh and USD. All participants completed two scenarios, and for each scenario, they proposed two distinct action plans">
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Participants saw a table with a family’s previous year electricity usage (here for the Wells family in Colorado) and were asked to allocate energy usage to meet a 15% reduction goal. The format of the reduction goal was manipulated to be either a percentage (15% reduction), kilowatt hours (5965 kWh), or USD ($656). Participants in the USD condition were provided with the conversion rate between kWh and USD. All participants completed two scenarios, and for each scenario, they proposed two distinct action plans</p>
</div>
</section>
</section>
<section id="results" class="level3">
<h3 data-anchor-id="results">Results</h3>
<p>All preprocessing and analyses were carried out in <code>R</code> version 4.4.3 <span class="citation" data-cites="rcoreteamLanguageEnvironmentStatistical2020">(<a href="#ref-rcoreteamLanguageEnvironmentStatistical2020" role="doc-biblioref">Team, 2020</a>)</span> and the Tidyverse package <span class="citation" data-cites="wickhamWelcomeTidyverse2019">(<a href="#ref-wickhamWelcomeTidyverse2019" role="doc-biblioref">Wickham et al., 2019</a>)</span>. Mixed Bayesian regressions were fit using the <code>brms</code> package <span class="citation" data-cites="burknerBrmsPackageBayesian2017">(<a href="#ref-burknerBrmsPackageBayesian2017" role="doc-biblioref">Bürkner, 2017</a>)</span>, with participants and family scenario set as random effects.</p>
<div id="tbl-s1-agg" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Summary statistics by reference class condition, based on participant-level averages. Exact Match Rate and Close Match Rate represent the mean percentage of trials (per participant) where the proposed reduction exactly matched or closely matched (±2% tolerance) the target goal (standard deviations in parentheses), respectively. Abs. Deviation and Log Abs. Deviation reflect the median (IQR in parentheses) of each participant’s absolute deviation from the target goal." prefix="" data-tblnum="1" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s1-agg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Study 1: Summary of planning accuracy by reference class</p>
</div>
</figcaption>
<div aria-describedby="tbl-s1-agg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 3%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Reference Class</th>
<th style="text-align: left;">N</th>
<th style="text-align: left;">Exact Match Rate(%)</th>
<th style="text-align: left;">Close Match Rate(%)</th>
<th style="text-align: left;">Abs. Deviation</th>
<th style="text-align: left;">Log Abs. Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">kWh</td>
<td style="text-align: left;">76</td>
<td style="text-align: left;">38 (45)</td>
<td style="text-align: left;">54 (45)</td>
<td style="text-align: left;">0.029 (0.117)</td>
<td style="text-align: left;">-3.69 (2.79)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percentage</td>
<td style="text-align: left;">67</td>
<td style="text-align: left;">22 (37)</td>
<td style="text-align: left;">40 (41)</td>
<td style="text-align: left;">0.056 (0.104)</td>
<td style="text-align: left;">-3.10 (1.87)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">USD</td>
<td style="text-align: left;">86</td>
<td style="text-align: left;">10 (28)</td>
<td style="text-align: left;">22 (33)</td>
<td style="text-align: left;">0.095 (0.094)</td>
<td style="text-align: left;">-2.40 (1.09)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Summary statistics by reference class condition, based on participant-level averages. Exact Match Rate and Close Match Rate represent the mean percentage of trials (per participant) where the proposed reduction exactly matched or closely matched (±2% tolerance) the target goal (standard deviations in parentheses), respectively. Abs. Deviation and Log Abs. Deviation reflect the median (IQR in parentheses) of each participant’s absolute deviation from the target goal.</p>
</div>
<p>The summary statistics in <a href="#tbl-s1-agg" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> suggest descriptive differences in planning accuracy across reference class conditions, with the kWh condition yielding the highest rates of exact matches, and lowest absolute deviations from the target reduction goal. However, use of these performance metrics to compare conditions is complicated by the non-normality of their distributions. Specifically, the substantial standard deviations associated with the match rates in <a href="#tbl-s1-agg" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a>, coupled with the visual evidence presented in <a href="#fig-s1-log-dist" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a>, underscore the markedly skewed, and potentially bi-modal distribution of the underlying planning errors.</p>
<p>In light of these distributional characteristics, we elected to bin planning performance into ordered accuracy levels (as shown in <a href="#tbl-s1-prop" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a>). Consequently, we binned individual trial outcomes into three distinct, ordered categories: “Exact match” (0% absolute error), “0.01-5% error” (minor deviations), and “Over 5% error” (larger deviations). This binned <code>accuracy_level</code> variable subsequently served as the dependent measure in our primary inferential analyses examining the impact of reference class on planning accuracy</p>
<div class="cell FigureWithNote" data-apa-note="Distribution of the log of the absolute error between the participant's action plan and the reduction goal. Left side plot separates across different reference class conditions (kWh, Percentage, USD). Right side plot separates by self-reported calculator use. A lower log absolute error suggests higher planning accuracy." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s1-log-dist" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="2">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s1-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 1: Planning Error Distributions</p>
</div>
</figcaption>
<div aria-describedby="fig-s1-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s1-log-dist-1.svg" class="img-fluid figure-img" width="1056">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Distribution of the log of the absolute error between the participant’s action plan and the reduction goal. Left side plot separates across different reference class conditions (kWh, Percentage, USD). Right side plot separates by self-reported calculator use. A lower log absolute error suggests higher planning accuracy.</p>
</div>
<div class="cell FigureWithNote" data-apa-note="The table shows the percentage of action-plans which fell into each accuracy level for each reference class condition (percentages of kWh, $, and USD columns reflect within condition percentages). " prefix="" data-tblnum="2" data-custom-style="FigureWithNote">
<div id="tbl-s1-prop" class="cell quarto-float quarto-figure quarto-figure-center" data-apa-note="The table shows the percentage of action-plans which fell into each accuracy level for each reference class condition (percentages of kWh, $, and USD columns reflect within condition percentages). " prefix="" data-tblnum="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s1-prop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 1: Categorization of Participants according to Accuracy Levels</p>
</div>
</figcaption>
<div aria-describedby="tbl-s1-prop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Accuracy Level</th>
<th style="text-align: left;">kWh</th>
<th style="text-align: left;">Percentage</th>
<th style="text-align: left;">USD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Exact match</td>
<td style="text-align: left;">38.5%</td>
<td style="text-align: left;">22.4%</td>
<td style="text-align: left;">10.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.01-5% error</td>
<td style="text-align: left;">22.7%</td>
<td style="text-align: left;">29.5%</td>
<td style="text-align: left;">25%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Over 5% error</td>
<td style="text-align: left;">38.8%</td>
<td style="text-align: left;">48.1%</td>
<td style="text-align: left;">64.8%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. The table shows the percentage of action-plans which fell into each accuracy level for each reference class condition (percentages of kWh, $, and USD columns reflect within condition percentages).</p>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>Group comparisons were conducted with Bayesian ordinal regression <span class="citation" data-cites="burknerOrdinalRegressionModels2019 kruschkeDoingBayesianData2014">(<a href="#ref-burknerOrdinalRegressionModels2019" role="doc-biblioref">Bürkner &amp; Vuorre, 2019</a>; <a href="#ref-kruschkeDoingBayesianData2014" role="doc-biblioref">Kruschke, 2014</a>)</span>. We modeled the ordered accuracy outcome as a function of the reference class condition, while controlling for random variation across participants and family scenarios (<a href="#eq-e1" class="quarto-xref">Equation&nbsp;1</a>).</p>
<p><span id="eq-e1"><span class="math display">
\text{Accuracy Level} \sim \text{Reference Class} + \text{Calculator} + (1|\text{id}) + (1|\text{Family Scenario})
\tag{1}</span></span></p>
<p>This approach allows the estimation of threshold parameters and regression coefficients that characterize how changes in predictor variables (such as the reference class: kWh, percentage, or USD) relate to probabilities of being in each accuracy category. We used a cumulative logit link function to model the ordered accuracy outcome, and we specified weakly informative priors <span class="citation" data-cites="kruschkeDoingBayesianData2014">(<a href="#ref-kruschkeDoingBayesianData2014" role="doc-biblioref">Kruschke, 2014</a>)</span> for the regression coefficients (normal distributions with mean 0 and standard deviation of 1) and for the cutpoints (normal distributions with a mean of zero and a standard deviation of 4.0). The approach can be used to estimate threshold parameters and regression coefficients that characterize how changes in predictor variables (such as the reference class: kWh, percentage, or USD) relate to probabilities of being in each level of accuracy (0% absolute error; 0.01-5% error; Over 5% error). Bayesian regression provides a probability distribution over the plausible values of the model parameters, allowing for a probabilistic interpretation of the uncertainty associated with these estimates.The width of the credible intervals (Bayesian equivalent of confidence intervals) derived from the posterior distribution directly indicates the degree of uncertainty in these effects.</p>
<div id="tbl-s1-reg" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Ordinal regression results. Positive coefficient estimates for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline." prefix="" data-tblnum="3" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s1-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p><strong>Experiment 1</strong>: Ordinal Regression Results of a Test of Differences between conditions in Accuracy Levels</p>
</div>
</figcaption>
<div aria-describedby="tbl-s1-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">CI_Lower</th>
<th style="text-align: left;">CI_Upper</th>
<th style="text-align: left;">pd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept[1]</td>
<td style="text-align: left;">-4.21</td>
<td style="text-align: left;">-5.90</td>
<td style="text-align: left;">-2.58</td>
<td style="text-align: left;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intercept[2]</td>
<td style="text-align: left;">-0.89</td>
<td style="text-align: left;">-2.49</td>
<td style="text-align: left;">0.71</td>
<td style="text-align: left;">0.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RefClass-Percentage</td>
<td style="text-align: left;">1.44</td>
<td style="text-align: left;">0.07</td>
<td style="text-align: left;">2.88</td>
<td style="text-align: left;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">RefClass-USD</td>
<td style="text-align: left;">3.13</td>
<td style="text-align: left;">1.81</td>
<td style="text-align: left;">4.50</td>
<td style="text-align: left;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">calc-UsedCalculator</td>
<td style="text-align: left;">-3.30</td>
<td style="text-align: left;">-4.80</td>
<td style="text-align: left;">-1.92</td>
<td style="text-align: left;">1.00</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Ordinal regression results. Positive coefficient estimates for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline.</p>
</div>
<div id="tbl-s1-ord" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition" prefix="" data-tblnum="4" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s1-ord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p><strong>Experiment 1</strong>: Odds ratios for group comparisons</p>
</div>
</figcaption>
<div aria-describedby="tbl-s1-ord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">odds_ratio</th>
<th style="text-align: left;">ci_lower</th>
<th style="text-align: left;">ci_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Percentage vs kWh</td>
<td style="text-align: left;">4.2</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">USD vs kWh</td>
<td style="text-align: left;">22.9</td>
<td style="text-align: left;">6.1</td>
<td style="text-align: left;">90</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition</p>
</div>
<p>As shown in <a href="#tbl-s1-reg" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a>, the reference class coefficients are positive for both the Percentage (Estimate = 1.44, 95% CI: 0.07 to 2.88, pd = 0.98) and USD (Estimate = 3.13, 95% CI: 1.81 to 4.50, pd = 1.00) conditions, relative to the kWh baseline. This indicates that, compared to the kWh condition, participants in both the Percentage and USD conditions were more likely to produce plans that fell into higher error categories. Moreover, the odds ratios (see <a href="#tbl-s1-ord" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>) suggest that the USD condition led to a notably higher likelihood of large errors compared to the kWh baseline (OR = 22.9), while the Percentage condition also demonstrated increased odds (OR = 4.2) but was somewhat less detrimental to accuracy than USD. These results align with our descriptive findings and further clarify that framing the target reductions in absolute kWh units may facilitate significantly more accurate planning. To evaluate the descriptive adequacy of our statistical model, we performed posterior predictive checks, a standard Bayesian technique wherein data simulated from the fitted ordinal model are compared against the observed data. As shown in <a href="#fig-s1-ppd" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a>, which compares the observed proportions of participant responses for each accuracy level (represented by bars) to the models predicted proportions (represented by points). The close correspondence between the observed bars and predicted points across different accuracy levels and reference class conditions suggests that the model adequately captures the patterns in the observed data.</p>
<div class="cell FigureWithNote" data-apa-note="Posterior predictive check for the Bayesian ordinal regression model. Blue bars show the observed frequencies for each accuracy level (Exact match, 0.01-5% error, and Over 5% error), dots with error bars represent the model predictions. The plot is faceted by reference class condition (kWh, Percentage, USD)." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s1-ppd" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="3">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s1-ppd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 1: Posterior Predictive Check</p>
</div>
</figcaption>
<div aria-describedby="fig-s1-ppd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s1-ppd-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Posterior predictive check for the Bayesian ordinal regression model. Blue bars show the observed frequencies for each accuracy level (Exact match, 0.01-5% error, and Over 5% error), dots with error bars represent the model predictions. The plot is faceted by reference class condition (kWh, Percentage, USD).</p>
</div>
<div class="cell FigureWithNote" data-apa-note="The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s1-els" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="4">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s1-els-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 1. Conditional effect of energy literacy on log absolute error</p>
</div>
</figcaption>
<div aria-describedby="fig-s1-els-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s1-els-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.</p>
</div>
<p>To further investigate individual factors that may influence planning accuracy, we examined the relationship between participants’ energy literacy scores and their performance on the task. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state. Results indicated a significant negative relationship between energy literacy and log absolute error (Estimate = -2.35, 95% CI: -2.88 to -1.81), suggesting that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (<a href="#fig-s1-els" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a>).</p>
</section>
<section id="experiment-1-discussion" class="level3">
<h3 data-anchor-id="experiment-1-discussion">Experiment 1: Discussion</h3>
<p>Experiment 1 examined how different numerical representations of energy reduction goals affected participants’ planning accuracy. In line with our hypothesis that absolute units would yield better accuracy, the kWh condition supported significantly more precise energy reduction plans than either the Percentage or USD conditions. Although the Percentage format was detrimental to accuracy relative to kWh, it was the USD condition that consistently produced the poorest outcomes, suggesting that monetary terms, while intuitive in everyday contexts, may not serve as effective reference classes for planning appliance-specific reductions in energy use.</p>
<p>Experiment 2 will extend these findings by examining whether additional variables, such as the difficulty of the reduction goal or the rounding of numerical values, further interact with reference class conditions, thereby providing a more comprehensive understanding of how to optimize energy information presentation for improved planning accuracy.</p>
</section>
</section>
<section id="experiment-2" class="level2">
<h2 data-anchor-id="experiment-2">Experiment 2</h2>
<section id="introduction-1" class="level3">
<h3 data-anchor-id="introduction-1">Introduction</h3>
<p>Building upon the preliminary evidence from Experiment 1, which indicated that representing energy reduction targets in absolute kilowatt-hour (kWh) units might yield superior planning accuracy relative to percentage or monetary formats, Experiment 2 was designed to further probe the robustness and nuances of this effect. A primary objective was to replicate the core finding regarding the influence of reference class on planning precision. Additionally, this second experiment sought to broaden the investigation by examining the potential impact of other task parameters; specifically, we manipulated the difficulty of the reduction goal (comparing a 10% versus a 15% target) and the granularity of the presented numerical usage data (using exact versus rounded figures).</p>
</section>
<section id="methods-1" class="level3">
<h3 data-anchor-id="methods-1">Methods</h3>
<p>In Experiment 2, 206 participants were recruited from Amazon Mechanical Turk, but data from 10 participants were corrupted due to experimenter error, and six were excluded because their error magnitudes were statistical outliers (error magnitudes exceeding 2.5 standard deviations from the group mean), leaving a final sample of 190 participants (102 males, 88 females, with an average age = 35.5, SD=9.5)</p>
<p>Experiment 2 employed a mixed experimental design with reference class (USD, Percentage, kWh) as a between-subjects factor, and two within-subjects factors: task goal (10% vs.&nbsp;15% reduction) and the presentation of last year’s usage data (exact vs.&nbsp;rounded numbers). The order of presentation of the goal, rounding, and family scenarios was counterbalanced across participants. As in Experiment 1, each participant completed the energy reduction planning task for two different family-state scenarios. In the “rounded” condition, both the family’s previous year usage and the state averages were rounded to the nearest whole number.</p>
</section>
<section id="results-1" class="level3">
<h3 data-anchor-id="results-1">Results</h3>
<div id="tbl-s2-agg" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Summary statistics by reference class condition, based on participant-level averages. Exact Match Rate and Close Match Rate represent the mean percentage of trials (per participant) where the proposed reduction exactly matched or closely matched (±2% tolerance) the target goal (standard deviations in parentheses), respectively. Abs. Deviation and Log Abs. Deviation reflect the median (IQR in parentheses) of each participant’s absolute deviation from the target goal." prefix="" data-tblnum="5" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s2-agg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 2: Summary of planning accuracy by reference class</p>
</div>
</figcaption>
<div aria-describedby="tbl-s2-agg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 3%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Reference Class</th>
<th style="text-align: left;">N</th>
<th style="text-align: left;">Exact Match Rate(%)</th>
<th style="text-align: left;">Close Match Rate(%)</th>
<th style="text-align: left;">Abs. Deviation</th>
<th style="text-align: left;">Log Abs. Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">kWh</td>
<td style="text-align: left;">68</td>
<td style="text-align: left;">44 (45)</td>
<td style="text-align: left;">52 (46)</td>
<td style="text-align: left;">0.022 (0.182)</td>
<td style="text-align: left;">-3.87 (3.12)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percentage</td>
<td style="text-align: left;">67</td>
<td style="text-align: left;">28 (36)</td>
<td style="text-align: left;">42 (42)</td>
<td style="text-align: left;">0.062 (0.138)</td>
<td style="text-align: left;">-3.22 (2.31)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">USD</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">20 (38)</td>
<td style="text-align: left;">29 (40)</td>
<td style="text-align: left;">0.102 (0.135)</td>
<td style="text-align: left;">-2.42 (1.52)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Summary statistics by reference class condition, based on participant-level averages. Exact Match Rate and Close Match Rate represent the mean percentage of trials (per participant) where the proposed reduction exactly matched or closely matched (±2% tolerance) the target goal (standard deviations in parentheses), respectively. Abs. Deviation and Log Abs. Deviation reflect the median (IQR in parentheses) of each participant’s absolute deviation from the target goal.</p>
</div>
<div class="cell FigureWithNote" data-apa-note="Distribution of the log of the absolute error between the participant's action plan and the reduction goal. Left side plot separates across different reference class conditions (kWh, Percentage, USD). Right side plot separates by self-reported calculator use. A lower log absolute error suggests higher planning accuracy." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s2-log-dist" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="5">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s2-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 2: Planning Error Distributions</p>
</div>
</figcaption>
<div aria-describedby="fig-s2-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s2-log-dist-1.svg" class="img-fluid figure-img" width="1056">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Distribution of the log of the absolute error between the participant’s action plan and the reduction goal. Left side plot separates across different reference class conditions (kWh, Percentage, USD). Right side plot separates by self-reported calculator use. A lower log absolute error suggests higher planning accuracy.</p>
</div>
<div id="tbl-s2-reg" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Ordinal regression results. Positive coefficients for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline. Coefficients for calc are in reference to the 'Used Calculator' group, coefficient for the pct_goal is in reference to the 10% goal, and coefficient for rounded is in reference to the 'Not Rounded' group." prefix="" data-tblnum="6" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s2-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;6</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p><strong>Experiment 2.</strong> Parameter estimates from the ordinal regression model</p>
</div>
</figcaption>
<div aria-describedby="tbl-s2-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">CI_Lower</th>
<th style="text-align: left;">CI_Upper</th>
<th style="text-align: left;">pd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept[1]</td>
<td style="text-align: left;">-1.45</td>
<td style="text-align: left;">-2.85</td>
<td style="text-align: left;">-0.07</td>
<td style="text-align: left;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intercept[2]</td>
<td style="text-align: left;">1.26</td>
<td style="text-align: left;">-0.09</td>
<td style="text-align: left;">2.65</td>
<td style="text-align: left;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RefClass-Percentage</td>
<td style="text-align: left;">1.02</td>
<td style="text-align: left;">-0.63</td>
<td style="text-align: left;">2.71</td>
<td style="text-align: left;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">RefClass-USD</td>
<td style="text-align: left;">2.27</td>
<td style="text-align: left;">0.53</td>
<td style="text-align: left;">3.98</td>
<td style="text-align: left;">0.99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">calc-NoCalculator</td>
<td style="text-align: left;">4.10</td>
<td style="text-align: left;">2.20</td>
<td style="text-align: left;">6.06</td>
<td style="text-align: left;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_goal15%</td>
<td style="text-align: left;">-0.39</td>
<td style="text-align: left;">-0.81</td>
<td style="text-align: left;">0.04</td>
<td style="text-align: left;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rounded-Rounded</td>
<td style="text-align: left;">-0.53</td>
<td style="text-align: left;">-0.96</td>
<td style="text-align: left;">-0.11</td>
<td style="text-align: left;">0.99</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Ordinal regression results. Positive coefficients for the reference class predictors indicate that those conditions are associated with higher error categories relative to the kWh baseline. Coefficients for calc are in reference to the ‘Used Calculator’ group, coefficient for the pct_goal is in reference to the 10% goal, and coefficient for rounded is in reference to the ‘Not Rounded’ group.</p>
</div>
<div id="tbl-s2-ord" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" data-apa-note="Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition" prefix="" data-tblnum="7" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-s2-ord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;7</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p><strong>Experiment 2.</strong> Odds ratios for group comparisons</p>
</div>
</figcaption>
<div aria-describedby="tbl-s2-ord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">comparison</th>
<th style="text-align: left;">odds_ratio</th>
<th style="text-align: left;">ci_lower</th>
<th style="text-align: left;">ci_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Percentage vs kWh</td>
<td style="text-align: left;">2.78</td>
<td style="text-align: left;">0.53</td>
<td style="text-align: left;">15.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">USD vs kWh</td>
<td style="text-align: left;">9.68</td>
<td style="text-align: left;">1.69</td>
<td style="text-align: left;">53.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">calc-NoCalculator</td>
<td style="text-align: left;">60.37</td>
<td style="text-align: left;">9.02</td>
<td style="text-align: left;">426.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">15% Goal vs 10% Goal</td>
<td style="text-align: left;">0.68</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rounded vs Not</td>
<td style="text-align: left;">0.59</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">0.9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Odds ratios greater than 1 indicate increased odds of falling into a worse accuracy category compared to the kWh condition</p>
</div>
<p>As in Experiment 1, accuracy was categorized into three ordinal levels: “Exact match” (0% error), “0.01-5% error,” and “Over 5% error”. The analyses for Experiment 2 employed a Bayesian ordinal regression model to examine the probability of falling into one of three accuracy categories (exact match, minor deviations, or substantial deviations) as a function of the reference class condition (kWh, Percentage, USD), while including pct_goal (10% vs.&nbsp;15%), rounded (exact vs.&nbsp;rounded usage data), and calculator usage as additional predictors. Random intercepts were specified for both participant and state (<a href="#eq-e2" class="quarto-xref">Equation&nbsp;2</a>). The model was fit using the brms package in R, with weakly informative priors for the regression coefficients and cutpoints <span class="citation" data-cites="kruschkeDoingBayesianData2014">(<a href="#ref-kruschkeDoingBayesianData2014" role="doc-biblioref">Kruschke, 2014</a>)</span>.</p>
<p><span id="eq-e2"><span class="math display">
\text{Accuracy} \sim \text{Reference Class} + \text{Calculator} + \text{Goal} + \text{Rounded} + (1|\text{id}) + (1|\text{Family Scenario})
\tag{2}</span></span></p>
<p>The ordinal regression analysis revealed that the USD reference class significantly increased the odds of higher error categories compared to the kWh reference class (OR = 9.68, 95% CI: [1.69, 53.4]). Participants in the USD condition were therefore substantially more likely to deviate from the target energy reduction goal compared to those in the kWh condition. In contrast, the Percentage condition’s odds ratio relative to kWh was more uncertain (OR = 2.78, 95% CI: [0.53, 15.0]), indicating that although there may be a trend toward reduced accuracy in the Percentage condition, the evidence was not definitive.</p>
<p>We also found that using rounded numbers modestly improved accuracy (Estimate = -0.53, 95% CI: [-0.96, -0.11]), with participants having 0.59 times the odds of falling into a worse accuracy category when working with rounded values. The more challenging 15% reduction goal was associated with slightly better performance compared to the 10% goal, Estimate = -0.39, 95% CI: [-0.81, 0.04], though this effect was relatively small. Consistent with Experiment 1, the use of a calculator had a large and significant effect on accuracy. The coefficient for calc-NoCalculator was Estimate = 4.10 95% CI: [2.20, 6.06], and the corresponding odds ratio was 60.37 (95% CI: [9.02, 426.4]), indicating that participants who did not use a calculator were substantially more likely to fall into higher error categories.</p>
<p><a href="#fig-s2-ame" class="quarto-xref" aria-expanded="false">Figure&nbsp;6</a> shows the marginal effects of refClass on each level of accuracy_level. These results reveal that switching from kWh to Percentage decreased the probability of an “Exact match” by an average of 7.0 percentage points, 95% CI: [-19.2, 4.2] and increased the probability of falling into the “Over 5% error” category by 6.9 percentage points, 95% CI: [-4.5, 18.6]. Similarly, switching from kWh to USD decreased the probability of an “Exact match” by 15 percentage points, 95% CI: [-26.7, -3.3], and increased the probability of “Over 5% error” by 16.5 percentage points, 95% CI: [3.7, 29.3].</p>
<div class="cell FigureWithNote" data-apa-note="The points represent the average change in the probability of each accuracy level when switching from the kWh reference class to Percentage (red) or USD (green). Error bars indicate 95% credible intervals. The results show that, compared to kWh, the Percentage format decreases the probability of an &quot;Exact match&quot; by 7.0% and increases the probability of &quot;Over 5% error&quot; by 6.9%. The USD format has a larger negative effect on &quot;Exact match&quot; (-14.7%) and a larger positive effect on &quot;Over 5% error&quot; (+16.5%). The effects on the &quot;0.01-5% error&quot; category are near zero for both comparisons." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s2-ame" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="6">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s2-ame-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;6</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 2. Average marginal effects of reference class on accuracy levels</p>
</div>
</figcaption>
<div aria-describedby="fig-s2-ame-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s2-ame-1.svg" class="img-fluid figure-img" width="1056">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. The points represent the average change in the probability of each accuracy level when switching from the kWh reference class to Percentage (red) or USD (green). Error bars indicate 95% credible intervals. The results show that, compared to kWh, the Percentage format decreases the probability of an “Exact match” by 7.0% and increases the probability of “Over 5% error” by 6.9%. The USD format has a larger negative effect on “Exact match” (-14.7%) and a larger positive effect on “Over 5% error” (+16.5%). The effects on the “0.01-5% error” category are near zero for both comparisons.</p>
</div>
<div class="cell FigureWithNote" data-apa-note="Posterior predictive check for the Bayesian ordinal regression model. Blue bars show the observed frequencies for each accuracy level (Exact match, 0.01-5% error, and Over 5% error), dots with error bars represent the model predictions. The plot is faceted by reference class condition (kWh, Percentage, USD)." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s2-ppd" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="7">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s2-ppd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;7</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 2. Posterior predictive check of the bayesian regression model</p>
</div>
</figcaption>
<div aria-describedby="fig-s2-ppd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s2-ppd-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Posterior predictive check for the Bayesian ordinal regression model. Blue bars show the observed frequencies for each accuracy level (Exact match, 0.01-5% error, and Over 5% error), dots with error bars represent the model predictions. The plot is faceted by reference class condition (kWh, Percentage, USD).</p>
</div>
<div class="cell FigureWithNote" data-apa-note="The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-s2-els" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="8">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-s2-els-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;8</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Experiment 2. Conditional effect of energy literacy on log absolute error</p>
</div>
</figcaption>
<div aria-describedby="fig-s2-els-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-s2-els-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. The plot shows the relationship between energy literacy score and log absolute error, controlling for random effects of participant and state. Higher energy literacy scores are associated with smaller deviations from the target reduction goal, indicating more accurate planning.</p>
</div>
<p>We once again examined the effect of energy literacy on planning accuracy. A Bayesian linear regression model was fit with log-transformed absolute error as the outcome variable and energy literacy score as the predictor, controlling for random effects of participant and state. This revealed a significant negative relationship between energy literacy and log absolute error (Estimate = -3.21, 95% CI: [-3.89 to -2.52]), indicating that participants with higher energy literacy scores tended to have smaller deviations from the target reduction goal, and thus more accurate plans overall (<a href="#fig-s2-els" class="quarto-xref" aria-expanded="false">Figure&nbsp;8</a>).</p>
</section>
<section id="experiment-2-discussion" class="level3">
<h3 data-anchor-id="experiment-2-discussion">Experiment 2: Discussion</h3>
<p>Experiment 2 aimed to build upon the findings of Experiment 1 by replicating the core manipulation of reference class. Additionally, it incorporated variables that might influence planning accuracy. These included goal difficulty and the way that the prior year’s usage was presented (rounded or exact). The results largely converged with those of Experiment 1, providing further converging evidence that presenting energy reduction goals in absolute units (kWh) facilitates more accurate planning compared to percentage-based or monetary formats.</p>
<p>Taken together, the results of Experiment 2 provide further support for the hypothesis that presenting energy reduction goals in absolute units (kWh) leads to more accurate planning compared to percentage-based or monetary formats.</p>
<p>The finding that the more challenging 15% reduction goal was associated with a slight improvement in accuracy is counterintuitive. It may be that participants put more effort into the task under this condition, or perhaps this is an artifact of the way that the task was presented. However, this effect was relatively small and thus should be explored in future research to confidently establish its existence. Furthermore, the magnitude of the effect size of this manipulation should be examined to better understand the practical implications of goal difficulty for energy conservation.</p>
<p>The large and significant effect of calculator use, consistent across both experiments, underscores the crucial role of tools that individuals are likely to employ in real-world settings. Finally, the consistent relationship between energy literacy and accuracy, observed across both experiments, highlights the potential value of educational interventions aimed at improving consumers’ understanding of energy concepts.</p>
</section>
</section>
<section id="general-discussion" class="level2">
<h2 data-anchor-id="general-discussion">General Discussion</h2>
<p>This study examined how different numerical representations of energy reduction goals influence consumers’ ability to create accurate energy conservation plans. Across two experiments, participants in the kWh conditions exhibited the smallest errors in allocating energy cuts across appliances, a result that consistently held even as scenario details varied. These results extend prior observations on the impact of numerical format on comprehension and decision-making <span class="citation" data-cites="gigerenzerSimpleToolsUnderstanding2003 reimerNumericCommunicationRisk2015">(<a href="#ref-gigerenzerSimpleToolsUnderstanding2003" role="doc-biblioref">Gigerenzer &amp; Edwards, 2003</a>; <a href="#ref-reimerNumericCommunicationRisk2015" role="doc-biblioref">Reimer et al., 2015</a>)</span>. But they move beyond simpler estimation tasks to show how these benefits persist in a goal-directed planning context. Notably, individuals with higher energy literacy performed better overall, a finding in line with previous work emphasizing the importance of domain knowledge for effective resource conservation <span class="citation" data-cites="attariPublicPerceptionsEnergy2010 canfieldPerceptionsElectricityuseCommunications2017">(<a href="#ref-attariPublicPerceptionsEnergy2010" role="doc-biblioref">Attari et al., 2010</a>; <a href="#ref-canfieldPerceptionsElectricityuseCommunications2017" role="doc-biblioref">Canfield et al., 2017</a>)</span></p>
<p>While prior research has suggested that consumers sometimes prefer monetary formats <span class="citation" data-cites="karjalainenConsumerPreferencesFeedback2011 nematiImpactInformationbasedInterventions2020">(<a href="#ref-karjalainenConsumerPreferencesFeedback2011" role="doc-biblioref">Karjalainen, 2011</a>; <a href="#ref-nematiImpactInformationbasedInterventions2020" role="doc-biblioref">Nemati &amp; Penn, 2020</a>)</span> or that monetary framing can improve appliance choices <span class="citation" data-cites="blaschBoundedlyRationalConsumers2019">(<a href="#ref-blaschBoundedlyRationalConsumers2019" role="doc-biblioref">Blasch et al., 2019</a>)</span>, our findings tentatively indicate that absolute energy units can facilitate the finer-grained calculations needed to plan specific usage cuts. This may be because kWh provide a more direct and less ambiguous representation of energy quantities, facilitating the necessary calculations for accurate planning. Moreover, although percentage-based targets might seem appealing from a goal-setting perspective, the additional step of converting percentages to tangible appliance reductions likely increases the chances for error <span class="citation" data-cites="fisher100BiasEffects2022">(<a href="#ref-fisher100BiasEffects2022" role="doc-biblioref">Fisher &amp; Mormann, 2022</a>)</span>. Research on consumer heuristics in energy judgments <span class="citation" data-cites="vandenbroekHeuristicsEnergyJudgement2019">(<a href="#ref-vandenbroekHeuristicsEnergyJudgement2019" role="doc-biblioref">Van Den Broek &amp; Walker, 2019</a>)</span> suggests that individuals gravitate toward concrete cues, and the directness of absolute units may align well with these heuristics. Similarly, the concept of “default units” <span class="citation" data-cites="herberzKiloWhatDefault2020">(<a href="#ref-herberzKiloWhatDefault2020" role="doc-biblioref">Herberz et al., 2020</a>)</span> further highlights how presenting energy data in a straightforward, standardized format can guide better consumer decisions. Nevertheless, it is unclear whether the observed benefits of absolute units (i.e., kWh) are genuinely attributable to their absolute nature, or if other characteristics of these units might be driving the effects (e.g., familiarity).</p>
<section id="limitations-and-future-directions" class="level3">
<h3 data-anchor-id="limitations-and-future-directions">Limitations and Future Directions</h3>
<p>A few constraints should be considered. First, each participant only completed a limited set of action plans (four total), which may not capture the variability of real-world decision processes. Second, although we recorded whether participants used calculators, we could not control how thoroughly they engaged in mathematical computations, nor could we track other external resources they might have consulted. Future studies could examine more extensive planning tasks, perhaps over multiple sessions, to see how stable these effects remain over time and repeated feedback cycles <span class="citation" data-cites="fischerFeedbackHouseholdElectricity2008">(<a href="#ref-fischerFeedbackHouseholdElectricity2008" role="doc-biblioref">Fischer, 2008</a>)</span>. In addition, investigating whether certain household types or income levels respond differently to monetary versus absolute energy frames could yield further practical guidance for targeting energy-reduction interventions. Finally, incorporating more explicit or automated prompts for appliance-specific tips <span class="citation" data-cites="tonkeProvidingProceduralKnowledge2024">(<a href="#ref-tonkeProvidingProceduralKnowledge2024" role="doc-biblioref">Tonke, 2024</a>)</span> could clarify how best to translate high-level goals into tangible actions in diverse contexts. By building on these avenues, subsequent work can refine how energy information is formatted and delivered, ultimately enhancing both the precision and feasibility of conservation planning.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="references" class="level2">
<h2 data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-abrahamseReviewInterventionStudies2005" class="csl-entry" role="listitem">
Abrahamse, W., Steg, L., Vlek, C., &amp; Rothengatter, T. (2005). A review of intervention studies aimed at household energy conservation. <em>Journal of Environmental Psychology</em>, <em>25</em>(3), 273–291. <a href="https://doi.org/10.1016/j.jenvp.2005.08.002">https://doi.org/10.1016/j.jenvp.2005.08.002</a>
</div>
<div id="ref-abrahamseEffectTailoredInformation2007" class="csl-entry" role="listitem">
Abrahamse, W., Steg, L., Vlek, C., &amp; Rothengatter, T. (2007). The effect of tailored information, goal setting, and tailored feedback on household energy use, energy-related behaviors, and behavioral antecedents. <em>Journal of Environmental Psychology</em>, <em>27</em>(4), 265–276. <a href="https://doi.org/10.1016/j.jenvp.2007.08.002">https://doi.org/10.1016/j.jenvp.2007.08.002</a>
</div>
<div id="ref-attariPublicPerceptionsEnergy2010" class="csl-entry" role="listitem">
Attari, S. Z., DeKay, M. L., Davidson, C. I., &amp; Bruine De Bruin, W. (2010). Public perceptions of energy consumption and savings. <em>Proceedings of the National Academy of Sciences</em>, <em>107</em>(37), 16054–16059. <a href="https://doi.org/10.1073/pnas.1001509107">https://doi.org/10.1073/pnas.1001509107</a>
</div>
<div id="ref-bednarRecognitionResponseEnergy2020" class="csl-entry" role="listitem">
Bednar, D. J., &amp; Reames, T. G. (2020). Recognition of and response to energy poverty in the <span>United States</span>. <em>Nature Energy</em>, <em>5</em>(6), 432–439. <a href="https://doi.org/10.1038/s41560-020-0582-0">https://doi.org/10.1038/s41560-020-0582-0</a>
</div>
<div id="ref-blaschBoundedlyRationalConsumers2019" class="csl-entry" role="listitem">
Blasch, J., Filippini, M., &amp; Kumar, N. (2019). Boundedly rational consumers, energy and investment literacy, and the display of information on household appliances. <em>Resource and Energy Economics</em>, <em>56</em>, 39–58. <a href="https://doi.org/10.1016/j.reseneeco.2017.06.001">https://doi.org/10.1016/j.reseneeco.2017.06.001</a>
</div>
<div id="ref-burknerBrmsPackageBayesian2017" class="csl-entry" role="listitem">
Bürkner, P.-C. (2017). Brms: <span>An R Package</span> for <span>Bayesian Multilevel Models Using Stan</span>. <em>Journal of Statistical Software</em>, <em>80</em>, 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>
</div>
<div id="ref-burknerOrdinalRegressionModels2019" class="csl-entry" role="listitem">
Bürkner, P.-C., &amp; Vuorre, M. (2019). Ordinal <span>Regression Models</span> in <span>Psychology</span>: <span>A Tutorial</span>. <em>Advances in Methods and Practices in Psychological Science</em>, <em>2</em>(1), 77–101. <a href="https://doi.org/10.1177/2515245918823199">https://doi.org/10.1177/2515245918823199</a>
</div>
<div id="ref-canfieldPerceptionsElectricityuseCommunications2017" class="csl-entry" role="listitem">
Canfield, C., Bruine De Bruin, W., &amp; Wong-Parodi, G. (2017). Perceptions of electricity-use communications: Effects of information, format, and individual differences. <em>Journal of Risk Research</em>, <em>20</em>(9), 1132–1153. <a href="https://doi.org/10.1080/13669877.2015.1121909">https://doi.org/10.1080/13669877.2015.1121909</a>
</div>
<div id="ref-dewatersEnergyLiteracySecondary2011" class="csl-entry" role="listitem">
DeWaters, J. E., &amp; Powers, S. E. (2011). Energy literacy of secondary students in <span>New York State</span> (<span>USA</span>): <span>A</span> measure of knowledge, affect, and behavior. <em>Energy Policy</em>, <em>39</em>(3), 1699–1710. <a href="https://doi.org/10.1016/j.enpol.2010.12.049">https://doi.org/10.1016/j.enpol.2010.12.049</a>
</div>
<div id="ref-farghaliStrategiesEnergyContext2023" class="csl-entry" role="listitem">
Farghali, M., Osman, A. I., Mohamed, I. M. A., Chen, Z., Chen, L., Ihara, I., Yap, P.-S., &amp; Rooney, D. W. (2023). Strategies to save energy in the context of the energy crisis: A review. <em>Environmental Chemistry Letters</em>, <em>21</em>(4), 2003–2039. <a href="https://doi.org/10.1007/s10311-023-01591-5">https://doi.org/10.1007/s10311-023-01591-5</a>
</div>
<div id="ref-fischerFeedbackHouseholdElectricity2008" class="csl-entry" role="listitem">
Fischer, C. (2008). Feedback on household electricity consumption: A tool for saving energy? <em>Energy Efficiency</em>, <em>1</em>(1), 79–104. <a href="https://doi.org/10.1007/s12053-008-9009-7">https://doi.org/10.1007/s12053-008-9009-7</a>
</div>
<div id="ref-fisher100BiasEffects2022" class="csl-entry" role="listitem">
Fisher, M., &amp; Mormann, M. (2022). The <span>Off</span> by 100% <span>Bias</span>: <span>The Effects</span> of <span>Percentage Changes Greater</span> than 100% on <span>Magnitude Judgments</span> and <span>Consumer Choice</span>. <em>Journal of Consumer Research</em>, <em>49</em>(4), 561–573. <a href="https://doi.org/10.1093/jcr/ucac006">https://doi.org/10.1093/jcr/ucac006</a>
</div>
<div id="ref-gigerenzerSimpleToolsUnderstanding2003" class="csl-entry" role="listitem">
Gigerenzer, G., &amp; Edwards, A. (2003). Simple tools for understanding risks: From innumeracy to insight. <em>BMJ</em>, <em>327</em>(7417), 741–744. <a href="https://doi.org/10.1136/bmj.327.7417.741">https://doi.org/10.1136/bmj.327.7417.741</a>
</div>
<div id="ref-gillConsumerMatchingCosts2022" class="csl-entry" role="listitem">
Gill, C. A., Atlas, S. A., Hardisty, D. J., &amp; Scott, S. P. (2022). Consumer matching costs to context: <span>Status</span> quo bias, temporal framing, and household energy decisions. <em>Journal of Consumer Behaviour</em>, <em>21</em>(5), 1018–1027. <a href="https://doi.org/10.1002/cb.2051">https://doi.org/10.1002/cb.2051</a>
</div>
<div id="ref-herberzKiloWhatDefault2020" class="csl-entry" role="listitem">
Herberz, M., Brosch, T., &amp; Hahnel, U. J. J. (2020). Kilo what? <span>Default</span> units increase value sensitivity in joint evaluations of energy efficiency. <em>Judgment and Decision Making</em>, <em>15</em>(6), 972–988. <a href="https://doi.org/10.1017/S1930297500008172">https://doi.org/10.1017/S1930297500008172</a>
</div>
<div id="ref-karjalainenConsumerPreferencesFeedback2011" class="csl-entry" role="listitem">
Karjalainen, S. (2011). Consumer preferences for feedback on household electricity consumption. <em>Energy and Buildings</em>, <em>43</em>(2-3), 458–467. <a href="https://doi.org/10.1016/j.enbuild.2010.10.010">https://doi.org/10.1016/j.enbuild.2010.10.010</a>
</div>
<div id="ref-kruschkeDoingBayesianData2014" class="csl-entry" role="listitem">
Kruschke, J. K. (2014). <em>Doing <span>Bayesian</span> data analysis: <span>A</span> tutorial with <span>R</span>, <span>JAGS</span>, and <span>Stan</span></em> (2nd ed.). Academic Press. <a href="https://doi.org/10.1016/B978-0-12-405888-0.09999-2">https://doi.org/10.1016/B978-0-12-405888-0.09999-2</a>
</div>
<div id="ref-memmottSociodemographicDisparitiesEnergy2021" class="csl-entry" role="listitem">
Memmott, T., Carley, S., Graff, M., &amp; Konisky, D. M. (2021). Sociodemographic disparities in energy insecurity among low-income households before and during the <span>COVID-19</span> pandemic. <em>Nature Energy</em>, <em>6</em>(2), 186–193. <a href="https://doi.org/10.1038/s41560-020-00763-9">https://doi.org/10.1038/s41560-020-00763-9</a>
</div>
<div id="ref-nematiImpactInformationbasedInterventions2020" class="csl-entry" role="listitem">
Nemati, M., &amp; Penn, J. (2020). The impact of information-based interventions on conservation behavior: <span>A</span> meta-analysis. <em>Resource and Energy Economics</em>, <em>62</em>, 101201. <a href="https://doi.org/10.1016/j.reseneeco.2020.101201">https://doi.org/10.1016/j.reseneeco.2020.101201</a>
</div>
<div id="ref-reimerNumericCommunicationRisk2015" class="csl-entry" role="listitem">
Reimer, T., Jones, C., &amp; Skubisz, C. (2015). Numeric <span>Communication</span> of <span>Risk</span>. In <em>The <span>SAGE</span> handbook of risk communication</em> (pp. 167–179).
</div>
<div id="ref-rcoreteamLanguageEnvironmentStatistical2020" class="csl-entry" role="listitem">
Team, R. C. (2020). <em>R: <span>A Language</span> and <span>Environment</span> for <span>Statistical Computing</span></em>. R: A Language and Environment for Statistical Computing.
</div>
<div id="ref-tonkeProvidingProceduralKnowledge2024" class="csl-entry" role="listitem">
Tonke, S. (2024). Providing procedural knowledge: <span>A</span> field experiment to encourage resource conservation in <span>Namibia</span>. <em>Journal of Development Economics</em>, <em>166</em>, 103202. <a href="https://doi.org/10.1016/j.jdeveco.2023.103202">https://doi.org/10.1016/j.jdeveco.2023.103202</a>
</div>
<div id="ref-vandenbroekHeuristicsEnergyJudgement2019" class="csl-entry" role="listitem">
Van Den Broek, K. L., &amp; Walker, I. (2019). Heuristics in energy judgement tasks. <em>Journal of Environmental Psychology</em>, <em>62</em>, 95–104. <a href="https://doi.org/10.1016/j.jenvp.2019.02.008">https://doi.org/10.1016/j.jenvp.2019.02.008</a>
</div>
<div id="ref-weberWhyCanOnly2018" class="csl-entry" role="listitem">
Weber, P., Binder, K., &amp; Krauss, S. (2018). Why <span>Can Only</span> 24% <span>Solve Bayesian Reasoning Problems</span> in <span>Natural Frequencies</span>: <span>Frequency Phobia</span> in <span>Spite</span> of <span>Probability Blindness</span>. <em>Frontiers in Psychology</em>, <em>9</em>, 1833. <a href="https://doi.org/10.3389/fpsyg.2018.01833">https://doi.org/10.3389/fpsyg.2018.01833</a>
</div>
<div id="ref-wickhamWelcomeTidyverse2019" class="csl-entry" role="listitem">
Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D., François, R., Grolemund, G., Hayes, A., Henry, L., Hester, J., Kuhn, M., Pedersen, T. L., Miller, E., Bache, S. M., Müller, K., Ooms, J., Robinson, D., Seidel, D. P., Spinu, V., … Yutani, H. (2019). Welcome to the <span>Tidyverse</span>. <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>